### ISSUE TITLE
Add support for this.base to use variables other than `this`

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#102]
Given this code:

```
members: {
  myMethod: function() {
    var that = this;
    var args = arguments;
    this.doSomething(function() {
      that.base(arguments);
    });
  }
```

this fails because `that.base` is not transpiled correctly, even though it is legitimate code.  The issue is that `this.base` is looked for explicitly, and qxcompiler needs to track valid aliases for `this`

**Comment by level420** [comment]
Lets say I have intergrated a foreign library which also supports the `base` method, and that points to a non qx object. What happens?

**Comment by johnspackman** [comment]
at the moment it will try to convert it to an absolute function call, which is impossible if you're not in a Qooxdoo class; the fix will have to track `this` and be sure that `this` is a Qooxdoo object
