### ISSUE TITLE
qx serve: serve temporary page

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#111]
If you execute `qx serve` it will tell you to "browse to http://localhost:8080". However, there is a certain lag in the transpilation/compilation of the application and the generation of the boot page, so that if you follow the suggestion too quickly, you will get a "Cannot GET ..." error message in the browser. 

I suggest that a temporary boot page is generated at the beginning of the compilation with a message that compilation has started and will be finished soon, which refreshes itself in regular intervals until the application and the final page has been generated. 

@johnspackman

**Comment by oetiker** [comment]
another option would be to only display the hint once the boot page is rendered ...

**Comment by cboulanger** [comment]
@oetiker Yes, that would be the easier solution.

**Comment by hkollmann** [comment]
solved with https://github.com/qooxdoo/qooxdoo-compiler/pull/263
