### ISSUE TITLE
qx.debug not set in Build version

### ISSUE THREAD

**Issue by FriedrichF** [qooxdoo/qooxdoo-compiler#115]
When i build my application with` qx compile --target build` the qx.debug Environment Variable is not set to false. It stays on True.

**Comment by cajus** [comment]
@johnspackman wasn't this discussed on gitter some time ago? Gitter seems to be un-searchable. Or I don't understand how it is supposed to work.

How to set env stuff from *config.json*?

**Comment by johnspackman** [comment]
Here's the docs: https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/cli/compile-json.md#environment-settings

**Comment by cboulanger** [comment]
@FriedrichF @johnspackman This seems outdated. Close?

**Comment by FriedrichF** [comment]
@cboulanger i am no longer involved in this project, so i am not able to validate this.

**Comment by cboulanger** [comment]
Closing this, reopen if necessary
