### ISSUE TITLE
ImageLoader SVG

### ISSUE THREAD

**Issue by FriedrichF** [qooxdoo/qooxdoo-compiler#117]
When i use SVG Images i get an Warning: `ImageLoader: Not recognized format of external image /path/to/image.svg`. The images are therefore not preloaded.
I added the `@asset /path/to/image.svg` which worked well in the old compiler.

**Comment by cboulanger** [comment]
@FriedrichF Does this problem persist in the latest versions of the compiler? CC: @johnspackman

**Comment by cboulanger** [comment]
No feedback since more than a month, closing.

**Comment by ofilippov** [comment]
Looks like current version of qx compiler doesn't fully support svg images from resources. As far as I see if we add ".svg" in line 31 of [ImageLoader.js](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/resources/ImageLoader.js) class then everything starts to work - svg images will have width and height.
