### ISSUE TITLE
`comparisonString` overriding does not work for Webfonts

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo-compiler#129]
The Webfont setting from the Manifest.json overrides the setting from the themes Font.js file. And you can only declare the comparisonString in the latter one.

The screenshot shows the problem for the FABrands webfont. The Font.js part is in the prototype and gets overriden by the instance setting (which comes from the manifest)
![webfont-problem](https://user-images.githubusercontent.com/5507035/35820120-05e760d2-0aa5-11e8-824c-6462742f19e6.png)

I am not really sure if this is a compiler problem or should be fixes in the qooxdoo sources.

**Comment by peuter** [comment]
One addition: when I manually remove the `qx.$$fontBootstrap` stuff from the generated boot.js evenrything works fine.

**Comment by cajus** [comment]
Webfonts defined in the Manifest are defined automatically. Adding conflicting names via *Fonts.js* is not supported and should not be done.

**Comment by peuter** [comment]
Ok I misread the documentation here, but then there is still one point remaining. If I add the comparisonString setting to the Manifest.json font definition I get:

```
Error: No such property: comparisonString
```

**Comment by peuter** [comment]
In the Manifest the property is called `testCharacters` using that adds the `comparisonString`to the generated `$$fontBootstrap` but it gets lost somewhere. The Font-Validator still uses the default comparison string.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo/pull/9527
