### ISSUE TITLE
Add support for recursive dependencies between contribs

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#135]
It would be really useful if a contrib was able to specify it's own dependencies, so that adding one contrib can cause it's dependents to be added to the compile.json.

While it should be possible to specify that a contrib depends on a specific branch of another contrib, IMHO care should be taken to avoid complex issues regarding versioning (eg the npm "dependency hell"), partly because we have very few modules out there at the moment and therefore have little real world problems to solve.

One way to handle this could be to collate a flat list of required contribs, and where there is a conflict (ie the same contrib listed twice with different versions) simply pick one (possibly preferring the master branch) and display a warning every single time that the `qx` command is run.  The developer would remove this warning by editing contrib.json to add a marker that says that they've selected the correct version.

**Comment by hkollmann** [comment]
solved with https://github.com/qooxdoo/qooxdoo-compiler/pull/273
