### ISSUE TITLE
'qx contrib install' doesn't seem to be picked up by compiler on first pass

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#146]
The following script snippet
```bash
qx contrib update
qx contrib install
qx compile ../../../build-env/travis/compile.json --all-targets 
```
has the following output:
```
Run 'qx contrib list' in the root dir of your project to see which libraries are compatible.
Installing cboulanger/qx-contrib-Dialog v1.3.3
Installing oetiker/UploadWidget v1.0.0
2018-02-15 20:26:44.049 bibliograph.Application: [181,8] Unresolved use of symbol dialog.Dialog.error
...
Failed to load meta for dialog.Dialog: Error: ENOENT: no such file or directory, open 'source-compiled/transpiled/dialog/Dialog.json'
```
If I re-run the script, the errors disappear. This seems to indicate that the first install doesn't seem to be picked up by the compiler. Need to investigate why that happens.

**Comment by hkollmann** [comment]
Is this a clean build? Could you try qx compile —clean? The compiler test nearly do the same ....

**Comment by cboulanger** [comment]
It's happening on a fresh debian VM with no preexisting data (see the [script](https://github.com/cboulanger/bibliograph/blob/develop/build-env/debian-ubuntu/install.sh)). It's strange.

**Comment by johnspackman** [comment]
when you run the app after the second compile, does it work?  Specifically, is dialog.Dialog defined at runtime?

**Comment by cboulanger** [comment]
Yes it does. Don't bother, maybe it's a quirk of the setup (this is part of an installation script), just wanted to document it in case it is reproducible. I've put in on my todo-List and will investigate it soon - need to finish a working prototype of my app right now.

**Comment by cboulanger** [comment]
No longer relevant, closing
