### ISSUE TITLE
PartLoader not working in build target

### ISSUE THREAD

**Issue by AmjadKh** [qooxdoo/qooxdoo-compiler#154]
Using source target, when PartLoader.require is triggered, a success request to include the file is done.
But using build target, when PartLoader.require is triggered, a request with error ERR_FILE_NOT_FOUND is done.
This means that qx compiler does not make a copy of js file that is defined as part in compile.json

**Comment by johnspackman** [comment]
Hi @AmjadKh - please can you retest with the latest compiler?  I think that this is fixed now ...

**Comment by hkollmann** [comment]
fixed in newer version
