### ISSUE TITLE
Translations don't move to 'unused' when removed

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo-compiler#161]
If you change a string inside your application (maybe due to active development when no translations have been made yet), the old string still sticks in the generated po file while the new string is added. This pollutes the po files on every compile run (see #158).

The original behaviour was to comment them out and keep them for reference.

**Comment by johnspackman** [comment]
The fix I've put here is to change the extracted comment to "NO LONGER USED" rather than comment it out - I hope that has the same effect, but avoids potential problems with parsing comments

**Comment by cboulanger** [comment]
Good enough for me, if someone wants a different behavior, we can discuss their PR to that effect.
