### ISSUE TITLE
Serve "source" in "qx serve"

### ISSUE THREAD

**Issue by pcdummy** [qooxdoo/qooxdoo-compiler#164]
I'm using `qx serve --target build --minify "off"` to server qooxdoo, when a error is thrown firefox gives me
a **nice link to the source** file but theres **no source file** as "qx serve" doesn't serve it by default.

As a workaround i symlinked my source to build-output which works great. 

Can we add the ability to serve source through "qx serve"?

**Comment by cboulanger** [comment]
@johnspackman @pcdummy Still relevant?

**Comment by johnspackman** [comment]
already fixed
