### ISSUE TITLE
Add qx contrib upgrade

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#182]
`qx contrib upgrade` should install the latest compatible version of all installed contribs. This is basically the same `qx contrib install <packagename>` for each contrib.

**Comment by hkollmann** [comment]
qx install - without package - do this for the configured version.

**Comment by cboulanger** [comment]
Yes, but to force upgrade you would need to delete the 'contrib' directory, which doesn't seem very convenient. A short script command could do just that and would be a future-proof API if things get implemented differently internally.

**Comment by cboulanger** [comment]
@johnspackman As `qx upgrade` doesn't work currently and can be confused with the new `qx contrib upgrade`, I think it would be better to remove `qx upgrade` and replace it later with `qx migrate` in order to avoid confusion.

**Comment by cboulanger** [comment]
Implemented by #349.
