### ISSUE TITLE
@ignore works in class documentation; fails in method documentation

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#186]
Adding the following lines into the documentation at the top of a class prevents warnings when `process.exit` is called in a method. Adding the same two lines in the documentation at the top of the method in which `process.exit` is called does not prevent the warning, but does when using the generator.

```
@ignore(process)
@ignore(process.exit)
```

**Comment by johnspackman** [comment]
this is already fixed
