### ISSUE TITLE
erroneous 'new' in extend key causes unhelpful error message

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#189]
If a class accidentally includes the `new` keyword in its `extend` definition, such as:
```
extend : new qx.ui.tabview.TabView,
```
then the following not-so-helpful error message is presented:
```
Failed to load meta for (NewExpression): Error: ENOENT: no such file or directory, open 'output/source/transpiled/(NewExpression).json'
```
The error message wouldn't be thoroughly awful -- or at least one might figure out what it meant -- if it included a file and line number, but it does not. The error message could likely be improved as well.

**Comment by cboulanger** [comment]
@johnspackman Is there an easy fix for this? Otherwise, I'd move it to the "future release" milestone.
