### ISSUE TITLE
Configuration files are read and parsed multiple times

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#190]
The method `getProjectData` in Command.js is called multiple times, e.g., by `getLibraryPath`, `getApplicationPath`. Each time it is called, it re-reads and re-parses the file. Is there any reason not to cache the data the first time it's read (maybe even doing it synchronously, once), and then returning the cached data on subsequent requests? (Or maybe have `parseJsonFile` cache the data based on the `filePath` variable)?

**Comment by hkollmann** [comment]
Could you prepare a PR? Thanks!

**Comment by cboulanger** [comment]
@oetiker This issue is related to #365 and your intention to provide central API access to the configuration files which incidentally checks the well-formedness of the files.  Should maybe happen before beta?

**Comment by cboulanger** [comment]
Closed in favor of #394
