### ISSUE TITLE
add option to NOT remove comments

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#194]
The qooxdoo compiler does not yet allow to build the qooxdoo api and qooxdoo test apps. The classic qooxdoo generator cannot deal with ES6 isms ... 

In order to resolve this problem in the short term one could use the qooxdoo compiler to transpile code to es5 and then run the generator on that code for generating the api and testing apps ... this almost works, but for problem that the compiler REMOVES all the comments from the transpiled code, even in source mode.

If the compiler would leave the comments in place, the classic generator should be able to work on the transpiled code ...

**Comment by hkollmann** [comment]
We are working on new apiviewer!
