### ISSUE TITLE
qx contrib install: more helpful message if no compatible release

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#196]
Currently, if a contrib doesn't have a release that is semver-compatible with the qooxdoo version used, the following message is displayed:

`'xxx/yyy has no stable release compatible with qooxdoo version 6.0.0-alpha-20180529.`

To make the message more helpful, add the following

`To install anyways, use --release x.y.z. Please ask the contrib maintainer to release a compatible version.`

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo-compiler/pull/273
