### ISSUE TITLE
eslint rules are too strict

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#200]
Right now, when I open the qooxdoo-compiler repo in PHPStorm which has excellent ESLint support, almost all files are marked as having multiple errors. We should either relax the rules or remove .eslintrc until we agree on (stricter?) rules and update the source files accordingly. Right now, it simply decreases readability of the code.

**Comment by hkollmann** [comment]
What's about a run of eslint lint -f? And a clean update for all afterthis?

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo-compiler/pull/284
