### ISSUE TITLE
Error compiling properties with init value expressions

### ISSUE THREAD

**Issue by sambu16** [qooxdoo/qooxdoo-compiler#206]
When compiling an existing project I get the error "Cannot interpret AST BinaryExpression" because some properties in a class have an init value which is an expression. 

```javascript
  properties: {
    minimum: {
      refine: true,
      init: Number.MAX_VALUE * -1
    },
    maximum: {
      refine: true,
      init: Number.MAX_VALUE
    },
    value: {
      refine: true,
      init: new Date().getMonth()+1
    }
  }
```

**Comment by cboulanger** [comment]
@sambu16 @johnspackman Is this still a problem or can the issue be closed?

**Comment by sambu16** [comment]
It does still seem to be an issue even with the latest released compiler:
`2019-05-01 05:28:37.729 Cannot interpret AST BinaryExpression at plaid.ui.form.MonthSpinner [32,34]`
I have worked around this myself by either setting the values in constructor or changing them as appropriate, e.g. -Number.MAX_VALUE
