### ISSUE TITLE
Add JSDoc parsing

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#22]
At the moment JSDoc is ignored, which is fine but does not allow for linting.  According to [the docs](http://www.qooxdoo.org/5.0.2/pages/development/api_jsdoc_ref.html) we historically support a subset of JSDoc with some non-standard changes, but ideally we would switch to using the standard library - even if we extend it with some non-standard, Qx-specific extensions it would be much better to not reinvent the wheel.

Does anyone know what the non-standard extensions are?

**Comment by cboulanger** [comment]
I am very much in favour of standards and existing toolchains. The problem is that the qooxdoo generator convention had switched the order of `@param`, so instead of `@param {string} somebody Somebody's name.` in JSDOC (see [here](http://usejsdoc.org/tags-param.html)), it is `@param dragSource {qx.bla.DragSource} the drag source that was dropped.` in qooxdoo (see docs). 

So we have the choice: supporting the old style by hacking JSDoc, or cleaning up the entire codebase and making it compatible (this should be doable with some clever regexpressions, shouldn't it?)

**Comment by johnspackman** [comment]
+1 for regex fixing the code - if that's the only difference, that sounds like an easy upgrade.  It's also something we could build into migration scripts or as a `qx` command

**Comment by cboulanger** [comment]
So should we agree on http://eslint.org (and its configuration files & executables) and http://usejsdoc.org (for specs, picked up by the new generator) for all our linting/documenting needs? A third question would be what beautifier/prettifier to use that would use the eslint configuration options (such as https://www.npmjs.com/package/es-beautifier, but there might be others)...

**Comment by derrell** [comment]
There's a lot of code that will break other than just our own. Every user application will also need to have its JSDoc altered. That's a non-backward-compatible change, so we must ensure that it occurs only for a major version release. That means that once we do this change, we won't be able to do any further minor version releases from master, so we should use some caution.

**Comment by oetiker** [comment]
I would also suggest to fix the code ... it will be hard once but then we are in sync ... much better than the keep distancing ourselves from the crowd in that respect.

**Comment by johnspackman** [comment]
I've been looking at this and while JSDoc is a great idea at first glance, it's not as simple as it sounds - firstly, the code at http://usejsdoc.org is focused on parsing the entire source file to produce the web pages for API documentation, but this means that it does not understand our classes and is instead designed to allow documentation to be extracted from explicit prototype-based inheritance or ES6 classes etc.  

What we would want is something that just parses the comment blocks, but something like half of the "@" tags would not apply to us - for example, there are tags to say what the super class is, what mixins have been used, etc.  

It *may* be possible to use JSDoc but it would require extensive changes to our code in order for it to pick up the correct structure and would be considerably more difficult to use than our current solution.  

As we already have the API viewer (the equivalent of JSDoc's web generation) and a parser that understands classes, the only thing left is a parser for comments... and that's not that hard really, so I've built one into qxcompiler (which supports a plugins for different tags).

We could consider changing the format for `@param` so that the type comes first though - as we're clearly modelled on JSDoc, it would be pretty annoying if our `@param` is the wrong way around compared to the rest of the world.  I'll code the `@param` parser so that it accepts either format
