### ISSUE TITLE
qx contrib: need to get rid of "v" in version names

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#226]
ATM, we have a mix of version names with and without the "v" prefix. This is confusing and should be settled to only have the version number without the prefix.

**Comment by oetiker** [comment]
the reason some people tag with 'v' as the first character is to prevent tags to be read as numbers by well-meaning scripting languages :)

**Comment by cboulanger** [comment]
@oetiker Yes, I agree, just that `qx contrib install --release` should accept both or enforce one way of stating the version number (probably without v). Currently you have to look carefully using `qx contrib list` which way the version number is specified - that is onerous.

**Comment by cboulanger** [comment]
The current implementation requires the "v" because it unambiguously identifies a release of a qooxdoo package on github. The "v" could be stripped in the list but that would only cause confusion. Closing.
