### ISSUE TITLE
qx contrib update: filter releases to avoid bloating of cache

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#229]
Currently, `qx contrib update --search` searches every single release of every repository that has a `qx-contrib` label. This is fine for a small number of contribs, but is not scalable once more people publish contribs and start releasing a large number of new versions. We need to find a filter algorithm to keep the cache manageable. 

Suggestion: Last 10 releases (maybe configurable via parameter) plus the highest stable version of each major version of a contrib.

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo-compiler/pull/333
