### ISSUE TITLE
Deprecate qooxdoo.json in favour of Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#230]
Currently, `qx contrib update` [checks for the existence of a file named `qoxdoo.json`](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/lib/qx/tool/cli/commands/contrib/Update.js#L198) in the root of a repository. This file allows the autodiscovery of multiple libraries within one repository. Currently, I think only @gnikolaidis/@ergobyte's qookery contrib uses this mechanism.

The question is if it is wise to have yet another metadata file or if a better solution would be to have one base library in the root of the repo which contains links to the sublibraries in its `Manifest.json` or `compile.json` file. This makes even more sense since now @johnspackman has extended the syntax of `Manifest.json` and `compile.json` to contain information on multiple apps. 

This should be settled in time before we go into beta.

**Comment by johnspackman** [comment]
IMHO having a `qooxdoo.json` is just fine - it exists solely as a signpost at the root of a repo, and is for qooxdoo.  That could work out to be quite useful for lots of reasons in the future (ie we might want to extend it to describe other things about the repo), but for now it's small, discrete file that has a specific purpose

**Comment by cboulanger** [comment]
Keeping `qooxdoo.json` for the time being.
