### ISSUE TITLE
type : "static" in mixin flags an error

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#240]
It is traditional that when only a `statics` section is provided, there be (or may be) an annotation that the file contains only static values and methods:
```
type : "static",
```

When this annotation exists in a mixin, the compiler flags as an error the fact that `type` is not a valid key. This should either be accepted since it may exist in much legacy code, or be flagged as a warning. (There's no real need for that annotation; it could be simply removed.)

**Comment by cboulanger** [comment]
@derrell @johnspackman Is this still the case or can the issue be closed?

**Comment by johnspackman** [comment]
@derrell I think that this may be wrong - I just coded the fix for this, but when I run my test app in the browser it breaks; 

Issue240.js:
```
qx.Class.define("testapp.Issue240", {
  extend: qx.core.Object,
  include: [ testapp.MIssue240 ]
});
```

MIssue240.js
```
qx.Mixin.define("testapp.MIssue240", {
  type: "static",
  
  statics: {
    A: 1
  }
});
```

Browser output:
```
Mixin.js:362 Uncaught Error: The configuration key "type" in mixin "testapp.MIssue240" is not allowed!
    at Object.__validateConfig (Mixin.js:362)
    at Object.define (Mixin.js:96)
    at MIssue240.js:1
    at MIssue240.js:1
qx.Mixin.__validateConfig() @ Mixin.js:362
qx.Mixin.define() @ Mixin.js:96
(anonymous) @ MIssue240.js:1
(anonymous) @ MIssue240.js:1
Class.js:867 Uncaught Error: The include definition in class "testapp.Issue240" contains an invalid mixin at position 0: undefined
    at Object.__validateConfig (Class.js:867)
    at Object.define (Class.js:187)
    at Issue240.js:1
    at Issue240.js:1
qx.Class.__validateConfig() @ Class.js:867
qx.Class.define() @ Class.js:187
(anonymous) @ Issue240.js:1
(anonymous) @ Issue240.js:1
Native.js:58 001085 qx.core.Init: Load runtime: 1085ms
```
