### ISSUE TITLE
add "deprecated" key to Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#241]
In order to allow contribs to be deprecated in favor of others, or to allow to rename contrib and/or change their namespace, would it make sense to add a key "deprecated" to `Manifest.json` which could contain the following information:
```json
'deprecated':
  'message': 'message to be shown during install and in qx contrib list',
  'supersededByBC': 'name of contrib which can be be used as a backwards-compatible drop-in replacement'
  'supersededBy': 'name of contrib which provides the same functionality, but might not be b/c'
}
```
This information then could be used by the compiler to automatically load a replacement (in case of "supersededByBC" or at least inform the user that s/he has to make changes.

If you have better ideas for naming the keys, or more information that could be put into the struct, they are welcome.

**Comment by johnspackman** [comment]
I like it; my only thought is that instead of having two `supersededBy` variants just a link to the new repo would be fine - if there are any issues around upgrading, they would be listed on the README there (and it means that if things change, only the new repo has to be updated)

**Comment by oetiker** [comment]
the supersededByBC sounds cool, but I wonder about the practicality of it ... after all the new contrib would likely have a new name and hence probably also a new namespace while keeping the methods and attributes BC ...  in that light johns pov makes sense ...

what would be nice if there was an option to record in my project that I am aware of the depreciation but that I still want to use the old version and would like to NOT be constantly reminded about it :)

**Comment by cboulanger** [comment]
What I like about differentiating between backwards-compatible and not b/c is that `qx contrib install` could simply download the b/c contrib - the use case is a simple renaming of the contrib. This would allow renaming without breaking people's installations. Maybe the key should be `renamed` then?

**Comment by cboulanger** [comment]
Although, thinking about it - if nothing changes except the name, one might as well use the old contrib until one upgrades. This would only make sense if the old contrib had to be pulled for some reason.

**Comment by cboulanger** [comment]
I think a more elegant and non-intrusive way is to do this with a GitHub topic. What about this: if GitHub topic "deprecated" is added to a repository, the contained libraries do no longer show up in `qx contrib list`, unless the `--all` parameter is passed. This will keep the library installable without "polluting" the list of contribs. This allows to rename contribs or move them into different namespaces without breaking existing installations.

**Comment by cboulanger** [comment]
This has been fixed.
