### ISSUE TITLE
allow qx install library@version

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#244]
Currently, we have the syntax `qx install library --release <release name>` where `<release name>` is usually a version number such as `v1.2.3`. Allow a syntax `qx install library@(v)1.2.3` to make it more intuitive and more similar to other tools like npm or composer.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo-compiler/pull/273
