### ISSUE TITLE
Missing css file in mobile app

### ISSUE THREAD

**Issue by eda2z** [qooxdoo/qooxdoo-compiler#247]
Executing the following commands:

qx create mtest --type mobile -I
cd mtest
qx compile

results in the following error:

2018-12-13 09:25:21.098 Error: ENOENT: no such file or directory, open '/srv/http/qx6/mtest/source/resource/mtest/css/custom.css'

The resulting app runs but it looks "ugly".  Am I missing something?  I am using the latest qx compiler on arch linux.

**Comment by cboulanger** [comment]
I can confirm this. It's odd. I first thought it was related to #243, but the resource folder is completely missing for some reason. I am looking into it.

**Comment by cboulanger** [comment]
I am not getting the error if I use the current master. Which version is displayed when you do `qx` without any arguments?

**Comment by eda2z** [comment]
qooxdoo-compiler v0.2.25.  I just did an 'npm -g update' this morning.  If I do a 2nd 'qx compile' without an intervening 'qx clean' then I don't get the error but the displayed result still looks 'strange'

**Comment by hkollmann** [comment]
2 runs of compile are necessary for the first time - the generated css files are not reckognized in the first run.
What's ugly? Do you have a picture?

**Comment by eda2z** [comment]
I was probably being harsh using the word ugly.  I guess I was expecting a "smoother" default theme.
![mtest](https://user-images.githubusercontent.com/6683633/49962939-4f360280-fedc-11e8-8a98-efcb1277f8f4.png)

**Comment by hkollmann** [comment]
Your are right. The custom.css file is not loaded.
Please try to insert an externalResource in your manifest.json 

`  "externalResources": {
        "script": [
         ],
        "css": [
          "your_app/css/custom.css"
        ]
   }
`
We should do this during create for mobile app

**Comment by cboulanger** [comment]
@hkollmann can you fix the [mobile skeleton](https://github.com/qooxdoo/qooxdoo-compiler/tree/master/tool/cli/templates/skeleton/mobile)?

**Comment by hkollmann** [comment]
It‘s on the list

Von meinem iPad gesendet

**Comment by eda2z** [comment]
Since I am actually trying to convert several mobile apps from 5.0.2 to the compiler, I copied over the files from old_app/source/resource/old_app/css to new_app/css and updated the Manifest.json.  But nothing happened so I'm guessing I placed the css directory in the wrong location.

**Comment by hkollmann** [comment]
css or scss files? I mobile app the css files are autogenerated into css dir. This is not changed.
You can try to generate a new mobile app with Compiler > 0.2.27, this generates an manifest.json with external resource.

**Comment by eda2z** [comment]
I am currently running v0.2.27 and except for the Manifest.json containing an externalResources key I see no difference from my original comment.  The app still looks the same and the only .css file I can find is under 
source-output/resource/qx/mobile/css/custom.css and it is a 0-length file.  The original ENOENT error refers to source/resource but there is no such directory -- there is a source/theme directory.

**Comment by hkollmann** [comment]
Compiler needs 2 runs.

1. compile source\theme\test\scss\custom.scss to source\resource\test\css\custom.css
2. copy source\resource\test\css\custom.css to source-output\resource\test\css\custom.css.

Could you try to create a new mobile project, run qx compile twice, run qx serve and look if it's working for you?

**Comment by eda2z** [comment]
I created a new mobile project (mtest), changed to that directory and ran

qx compile source/theme/mtest/scss/custom/scss

I also tried it with a 2nd argument of source/resource/test/css/custom.css; and I tried just using sass.  In each case I got the following error message:

Error: Failed to load [object Object]: SyntaxError: Cannot tokenize symbol <@> at 1:1
@import "common/all";
^
    at defaultConstructor.__loadJson (/home/ed/.nvm/versions/node/v8.14.0/lib/node_modules/qxcompiler/lib/qx/tool/cli/commands/MConfig.js:256:15)
    at <anonymous>

I re-installed nvm/npm/qx today but maybe I've got something configured incorrectly?  I am on a Linux box and judging by your response it looks like you are on Windows.

**Comment by hkollmann** [comment]
Please run qx compile without any arguments!

Von meinem iPad gesendet

**Comment by eda2z** [comment]
I first did an 'npm -g update' and noticed that I now have v0.2.28.  I then repeated my steps of building a new mtest and compiling it twice.  Running 'qx serve' and also accessing the app thru apache showed no change.  The app runs but it looks like it is using some default css/theme.  Since I do have versions of my apps running under 5.0.2, I did the following:
created a new mtest app and compiled it twice; created the directory mtest under source-output/resource (since it did not exist); copied the 3 directories (css, icon, scss) from one of my old apps (source/resource/oldapp).  The app now looks like it is themed.

**Comment by hkollmann** [comment]
Wich Linux do you use? Is npm sass working?
@team: Could someone working with linux try to create and compile a mobile app?

Von meinem iPhone gesendet

**Comment by eda2z** [comment]
I am running on Arch linux and installing gnome-builder caused ruby-sass (version 3.6.0-1) to also be installed.  I uninstalled it and installed npm sass -- the compiler install instructions never mentioned the need for it.  Doing this had no affect, there is still no theme and npm sass complains about "@import "common/all" -- Can't find stylesheet to import.

**Comment by hkollmann** [comment]
do you have a docker container with archlinux and node?

**Comment by eda2z** [comment]
No.  Arch is my base operating system.  I did not have any problems with the compiler for desktop, only mobile.

**Comment by eda2z** [comment]
I just did an "npm -g update" which got me version v.0.2.23 and it looks like it solves my original issue.  Thanks for fixing this.  Should I be closing this issue?

**Comment by hkollmann** [comment]
muat be v0.2.33.
yes please close the issue

**Comment by eda2z** [comment]
Fixed with v0.2.23.
