### ISSUE TITLE
Add json schema for compile.json & Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#259]
For validation and convenient autocomplete in IDEs, it would be good to have a JSON schema for `compile.json` and `Manifest.json`. This would also induce us to keep documention of these files up-to-date.

**Comment by cboulanger** [comment]
@johnspackman

**Comment by cboulanger** [comment]
https://json-schema.org/specification.html

**Comment by thron7** [comment]
There is also an old schema spec for the old `config.json` in the repo:

https://github.com/qooxdoo/qooxdoo/blob/master/tool/data/config/config_schema.json

Might help as another resource.

**Comment by cboulanger** [comment]
To be implemented by #365
