### ISSUE TITLE
doc naming confusion

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#266]
I found documentation of compile.json in cli/compile-json.md file and documentation of manifest.json in compiler/Manifest.md. That has confused me a little bit. Should'nt both be in the same directory and have an equal name schema? I suggest to move compile-json.md to compiler dir and rename manifest.md to manifest-json.md

**Comment by cboulanger** [comment]
Since they are both configuration files, maybe they should both be in a directory `configuration`? Then documentation on other things which has config values can refer to there...

**Comment by hkollmann** [comment]
solved with https://github.com/qooxdoo/qooxdoo-compiler/pull/275
