### ISSUE TITLE
Remove qooxdoo.json as lookup file for multiple libraries per contrib

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#269]
If a contrib contains several libraries, they can be discovered by `qx contrib update` via a `qooxdoo.json` file ([documentation](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/cli/contrib.md#qooxdoojson)). This is an additional file to maintain and to document. Instead, the information should be integrated into the `provides.libraries` section of the top-level `Manifest.json` file in a contrib.

**Comment by johnspackman** [comment]
Why?  This seems wrong to me.  A Manifest.json is for libraries, but `qooxdoo.json` is for discovering libraries - they share none of the same information and are for completely different purposes.

**Comment by cboulanger** [comment]
After clearing up our different understanding about "what a contrib really is" I now think @johnspackman is right here. :-)
