### ISSUE TITLE
--watch is not working any longer

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#278]

**Comment by hkollmann** [comment]
I have an idea what has happend. Will fix it over the Weekend

**Comment by johnspackman** [comment]
Have you tried it on my PR for https://github.com/qooxdoo/qooxdoo-compiler/pull/277?  @zaucker mentioned it this morning but I couldn't reproduce it.  I've made a load of changes for promise support in that PR, including some work in that area

**Comment by hkollmann** [comment]
I will check this after merge - the issue was just a reminder

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo-compiler/pull/285
