### ISSUE TITLE
Respect `environment` key in `qx.Class`

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#29]
`qx.Class.define` support `environment`, this is currently ignored and needs to be fixed

**Comment by mbgonicus** [comment]
Probably related: issue #49 and pr #67

**Comment by mbgonicus** [comment]
Probably solved?

**Comment by johnspackman** [comment]
no not yet - the issue is that classes can have an `"environment"` block, but that's hardly used at the moment (but would be very useful to switch to, especially for accurate dependency calculations)

**Comment by cboulanger** [comment]
We also need this so that libraries can provide default values for environment variables. Otherwise, if the including app doesn't state the defaults in their `compile.json` environment sections, you get "X is not a valid key. Please see the API-doc…." warnings if the env vars are used in the code.

**Comment by johnspackman** [comment]
I think that this is actually fixed after all (by https://github.com/qooxdoo/qooxdoo-compiler/pull/142); the environment key is respected for @cboulanger 's use case
