### ISSUE TITLE
Exception with Application named "wm.qx.mutablelist"

### ISSUE THREAD

**Issue by pcdummy** [qooxdoo/qooxdoo-compiler#3]
Hi John,

i try to compile an application named "wm.qx.mutablelist" which is a contrib and a demo at once,
it fails to compile that because the result of https://github.com/johnspackman/qxcompiler/blob/master/lib/qxcompiler/targets/Target.js#L228 is "wm" and not "wm.qx.mutablelist".

Do you have an idea how we could solve that?

**Comment by johnspackman** [comment]
I think we'd have to search for the namespace, eg look for a library with "wm" namespace, then "wm.qx", then "wm.qx.mutablelist".

**Comment by pcdummy** [comment]
Can't we do something like `analyzer.findLibraryFor('wm.qx.mutablelist')` and then see where the Namespace of the library is exact `wm.qx.mutablelist`?

**Comment by cboulanger** [comment]
@pcdummy @johnspackman Is this issue still relevant?

**Comment by johnspackman** [comment]
i'm pretty sure that this was fixed a long time ago, closing
