### ISSUE TITLE
"Unresolved use of symbol" for default argument

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#309]
Given this code:
```javascript
qx.Class.define("cboulanger.eventrecorder.UiController", {
  extend: qx.ui.window.Window,
  construct: function(caption="Event Recorder") {
    this.base(arguments);
    // assign id to this widget from caption
    const objectId = caption.replace(/ /g, "").toLocaleLowerCase();
```
the compiler complains "Unresolved use of symbol caption.replace"

**Comment by hkollmann** [comment]
Compiling qx with qx gives another example:

qx.tool.cli.commands.Command: [380,53] Unresolved use of symbol replaceInFilesArr.length

    async migrate(fileList, replaceInFilesArr=[], annouceOnly=false) {
      let quiet = this.argv.quiet;
      if (qx.lang.Type.isArray(fileList)) {
        let filesToRename = this.checkFilesToRename(fileList);
        if (filesToRename.length) {
          if (annouceOnly) {
            // announce migration
            console.warn(`*** Warning: Some metadata filenames have changed. The following files will be renamed:`);
            for (let [newPath, oldPath] of filesToRename) {
              console.warn(`    '${oldPath}' => '${newPath}'.`);
            }
          } else {
            // apply migration
            for (let [newPath, oldPath] of filesToRename) {
              try {
                await fs.renameAsync(oldPath, newPath);
                if (!quiet) {
                  console.info(`Renamed '${oldPath}' to '${newPath}'.`);
                }
              } catch (e) {
                console.error(`Renaming '${oldPath}' to '${newPath}' failed: ${e.message}.`);
                process.exit(1);
              }
            }
          }
        }
      }
      if (qx.lang.Type.isArray(replaceInFilesArr) && replaceInFilesArr.length) {
        for (let replaceInFiles of replaceInFilesArr) {
          if (annouceOnly) {
            console.warn(`*** In the file(s) ${replaceInFiles.files}, '${replaceInFiles.from}' will be changed to '${replaceInFiles.to}'.`);
            return;
          }
          try {
            let results = await replace_in_file(replaceInFiles);
            if (!quiet) {
              let files = results.filter(result => result.hasChanged).map(result => result.file);
              console.info(`The following files were changed: ${files.join(", ")}`);
            }
          } catch (e) {
            console.error(`Error replacing in files: ${e.message}`);
            process.exit(1);
          }
        }
      }
    }
  }
});

**Comment by hkollmann** [comment]
spread operator is not working either:

qx.tool.cli.commands.Compile: [470,8] Unresolved use of symbol srcs.forEach

      function mergeArray(dest, ...srcs) {
        srcs.forEach(function(src) {
          if (src) {
            src.forEach(function(elem) {
              if (!qx.lang.Array.contains(dest, src)) {
                dest.push(elem);
              }
            });
          }
        });
        return dest;
      }
