### ISSUE TITLE
broken compatibility evaluation

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#343]
just realized that `npx qx contrib list` shows `v0.9.0` as the latest version of the `eventrecorder`, but when I install it I get `v0.8.0` as this seems to be the `latest compatible version` ...

my guess is that the dependencies to `ergobyte/qookery/qookery` and friends cause confusion since they do not correspond to contribs but are libraries included in the `ergobyte/qookery` ... 

in any event, once I had installed v0.9.0 by force

```
npx qx contrib install cboulanger/eventrecorder@v0.9.0
```

all of ergobyte got installed and I could compile my application just fine.

**Comment by cboulanger** [comment]
I think the issue is solved, it was a mismatch between version number in `Manifest.json` and the release tag. #345 improves `qx contrib publish` to prevent that.
