### ISSUE TITLE
Allow "qx contrib install my/library@<commit  hash>"

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#350]
In order to make development of contribs easier, we should allow to reference a commit directly, bypassing the contrib cache altogether. This way, code trees can be referenced without having to wait for releases to be made (and registered in the cache).

**Comment by oetiker** [comment]
could we  make this 'tree-ish' instead of commit hash ?

**Comment by cboulanger** [comment]
True, makes more sense!

**Comment by hkollmann** [comment]
Done with #351,

**Comment by cboulanger** [comment]
Thanks. I am reopening because I saw this:
https://help.github.com/en/articles/getting-permanent-links-to-files
It says: "You can put any identifier that can be resolved to a commit in the URL, including branch names, specific commit SHAs, or tags!"
Maybe this can really simplify our dowload URL resolution issue.

**Comment by cboulanger** [comment]
That is, one URL template `https://github.com/<user_name>/<repo_name>/blob/<id>/` would cover both release tags and commit hashes, and we can get rid of the currently hardcoded "tree/" prefix .

**Comment by cboulanger** [comment]
Although `/bob/` doesn't work because we need the ZIP file.

**Comment by oetiker** [comment]
https://github.com/qooxdoo/qooxdoo-compiler/archive/<tree-ish>.zip

**Comment by hkollmann** [comment]
Could we close this now?

**Comment by cboulanger** [comment]
Yes, it’s implemented now. Closing.
