### ISSUE TITLE
Rename "contrib" to something else

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#369]

**Comment by cboulanger** [comment]
This is taken from #279 since it addresses a separate issue.

The term "contrib" historically referred to user-contributed libraries. Since we now ship central functionality of the framework, such as the apiviewer as "contribs" (with more to come), it no longer makes sense to talk about "contribs", a weird name anyways that needs explaining. We should be using a more self-explanatory name. 

"contribs" currently refer to 
 - libraries (or collection of libraries) which act as "plugins" or "modules"
 - which are, for the most part, but not always (such as local or remote libraries accessible by URL) registered in a central database so they can easily be installed

we need a term X that would be able to express:
 - a "X" can contain one or more libraries.
 - via the CLI, you install the "X" (with the contained library / all contained libraries) using `qx X install owner/repo`, or a "sub-X" (which would be just one library) via `qx X install owner/repo/path`

Current candidates:
 - "module"
 - "extension"

**Comment by oetiker** [comment]
* package

**Comment by hkollmann** [comment]
package

**Comment by hkollmann** [comment]
With a shortcut to pack or p.

**Comment by oetiker** [comment]
pkg ?

**Comment by cboulanger** [comment]
@johnspackman @derrell @level420 What do you think?

**Comment by johnspackman** [comment]
package & pkg would be fine by me

**Comment by level420** [comment]
I‘m also in favor of package. 
We then could have library packages, theme packages, widget packages etc. 

To be honest: I‘m currently still using generator.py and manually downloaded and manually unpacked contribs which I‘ve referenced manually in the projects config.json. Never used auto-magic things for that.

So I currently trust those working hard to bring the compiler forward. Thank you for that!

**Comment by derrell** [comment]
I'm good with package and pkg. Far more appropriate names, IMO, than contrib.

**Comment by cboulanger** [comment]
Very well. `package`/`pkg` it is, then. Hope to be able to work on it this weekend.

@level420 Once libraries start becoming more modular (See already the qooxdoo demos) and thus depending on each other more heavily, the new functionality will be indispensable. You probably wouldn't want to to be managing 10+ libraries and their dependencies  manually... :-) This will allow to publish small interoperable building blocks of qooxdoo code which will be a huge improvement for the community.

**Comment by cboulanger** [comment]
Implemented by #380
