### ISSUE TITLE
translation reported to not work

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#37]

**Comment by cajus** [comment]
Looks like just the CLDR stuff is in the locales. The contents of the PO files is not there.

**Comment by mbgonicus** [comment]
I guess this is solved via #90 ?

**Comment by johnspackman** [comment]
possibly - it's on my todo list to have a thorough test of translations (I have the luxury of not having to to i18n in the day job), so if people like you and @cajus are finding that it's working "just fine" then we can close this.

**Comment by pcdummy** [comment]
Think we can close this, translations work fine with latest qxcompiler from git..

Only thing is:

```
#: proxmox/content/lxc/View.js:29 proxmox/content/lxc/Summary.js:31
#: proxmox/page/lxc/Summary.js:31 proxmox/page/lxc/Summary.js:28
#: proxmox/page/lxc/Summary.js:24 proxmox/page/lxc/Summary.js:25
#: proxmox/page/qemu/Summary.js:24 proxmox/page/node/Summary.js:24
#: proxmox/page/datacenter/Search.js:16 proxmox/page/datacenter/Search.js:19
#: proxmox/page/lxc/AbstractLxc.js:25 proxmox/page/Lxc.js:27
#: proxmox/page/Lxc.js:31 proxmox/page/Lxc.js:24 proxmox/page/Lxc.js:28
#: proxmox/page/Node.js:28 proxmox/page/Node.js:24 proxmox/page/Qemu.js:28
#: proxmox/page/Qemu.js:24
msgid "Start"
msgstr "Start"
```

As you see i have multiple mentions on different lines everytime the line changes.

**Comment by cboulanger** [comment]
@pcdummy Would you create a separate issue for this? I see the same problem - multiple entries for the same line.

**Comment by pcdummy** [comment]
Done #163
