### ISSUE TITLE
compiler does not find qooxdoo sdk on a diffent drive.

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#371]
Describe the bug
qx compiler in driver other than c: \
d:\qxdemo>qx compile
Error: Error: Empty Manifest.json in library at /Users/pccristiano/AppData/Roaming/npm/node_modules/qxcompiler/node_modules/qooxdoo-sdk/framework
at qx.tool.compiler.files.Utils.correctCase.then.then.then.data (C:\Users\pccristiano\AppData\Roaming\npm\node_modules\qxcompiler\lib\qx\tool\compiler\app\Library.js:149:19)
at 
To Reproduce
c:\npm install -g qxcompiler
d:\mkdir qxdemo
d:\cd qxdemo
d:\qxdemo\qx create qxdemo --out . --type desktop --noninteractive
d:\qxdemo\qx compile
d:\qxdemo>qx compile
Error: Error: Empty Manifest.json in library at /Users/pccristiano/AppData/Roaming/npm/node_modules/qxcompiler/node_modules/qooxdoo-sdk/framework
at qx.tool.compiler.files.Utils.correctCase.then.then.then.data (C:\Users\pccristiano\AppData\Roaming\npm\node_modules\qxcompiler\lib\qx\tool\compiler\app\Library.js:149:19)
at 
Desktop (please complete the following information):
OS: Windows 10

**Comment by hkollmann** [comment]
first mentioned here: https://github.com/qooxdoo/qooxdoo/issues/9664.

**Comment by hkollmann** [comment]
I think it's a problem of using upath. upath translates path's to unix style and removes the drive letters.
We should rethink using of upath.

**Comment by cboulanger** [comment]
https://www.npmjs.com/package/upath#why- says: "Note that using Unix / on Windows works perfectly inside nodejs (and other languages), so there's no reason to stick to the Windows legacy at all."

**Comment by cboulanger** [comment]
The examples show that the letter is preserved:
`'c:\\windows\\nodejs\\path'`        --->      `'c:/windows/nodejs/path'`  
 `path.normalize()` gives `'c:\windows\nodejs\path'`

**Comment by hkollmann** [comment]
upath was just an guess.
Then it's needs some debugging. It's on the list.
