### ISSUE TITLE
@ignore did not work for unknown variables

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#38]
During compile of qx.io.remote.Rpc you get an error message:
2017-11-05 12:04:49.437 qx.io.remote.Rpc: [127,8] Unresolved use of symbol qx.core.ServerSettings

qx.core.ServerSettings has an entry @ignore in Rpc.js.

Steps to reproduce:
- create an new Project `qx create test`
- add  @require(qx.io.remote.Rpc) in Application.js
- `qx compile`
 
Versions: qooxdoo-cli v0.1.30, qooxdoo-compiler v0.1.26

**Comment by johnspackman** [comment]
fixed in next release (0.1.27)
