### ISSUE TITLE
Refactor utils and integrate json-to-ast

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#386]
Currently there are `qx.tool.compiler.utils.*` and `qx.tool.cli.Utils`, plus the `json-to-ast` module which is a git dependency; AFAICR the compiler and cli code use each others utils, because a lot (most? all?) of it is more generic than just one specific tool.

The `json-to-ast` module is a branch which has been an outstanding PR for nearly 2 years.

I propose that we refactor the utils into a generic `qx.tool.utils` namespace, and pull the `json-to-ast` code in there too, removing the extra dependency on a git branch.

This probably should not be done until https://github.com/qooxdoo/qooxdoo-compiler/pull/380 is merged

**Comment by johnspackman** [comment]
From gitter:

The compiler directory structure is quite confusing. WE
We have "lib", "resource", "tool", "utils". Wouldn't it be better to mirror the framework folder organization -> source/class/qx/tool, source/resource/qx/tool/(cli|compiler)/(serve|templates|utils) ?
That would also prepare a later integration, if that is still on the horizon.

**Comment by cboulanger** [comment]
#380 is merged, but please wait until #394 is implemented (currently in branch https://github.com/qooxdoo/qooxdoo-compiler/tree/cboulanger-new-config-system).

**Comment by hkollmann** [comment]
Done with #416
