### ISSUE TITLE
Migrate unit tests to use testtapper

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#400]
The current unit tests use tape, which is not ideal - the unit tests should be migrated to use the standard test framework and qxl.testtapper

**Comment by johnspackman** [comment]
@cboulanger @oetiker although we talked about this on gitter, please can you clarify - does the current test framework support node?  I vaguely recall that it was "planned" only?

The tape based unit tests in qx currently are not browser based, so im wondering how they would fit in with qxl.testtapper

**Comment by cboulanger** [comment]
The qooxdoo unit tests do not support a async tests yet and isn’t very useful for node yet. But Tobi is working on it , I think ....

**Comment by cboulanger** [comment]
https://github.com/qooxdoo/qxl.testtapper/pull/7 😄

**Comment by cboulanger** [comment]
Done.
