### ISSUE TITLE
Merge 'new qx.tool.cli.Utils.UserError' and 'qx.tool.compiler.utils.UserError'

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#401]
1. `qx.tool.cli.Utils.UserError` returns a constructor that needs to be initialized with `new` 
2. `qx.tool.compiler.utils.UserError` is a factory function that returns an error instance

I would argue to use 1) because people are used to write `throw new CustomError` and not `throw customErrorFactoryFunction`

**Comment by cboulanger** [comment]
Wait, no, that is not correct. Both return an instance, because BOTH are factory functions which instantiate an error object and then remove the stack trace. 

We should replace BOTH factory function with a real class which inherits from `Error` and removes the stack in the constructor.

**Comment by cboulanger** [comment]
Both `throw new qx.tool.cli.Utils.UserError("Oh No!");` and `throw qx.tool.cli.Utils.UserError("Oh No!");` works because in the first case it simply instantiates a new o object from the new object.

**Comment by hkollmann** [comment]
qx.tool.cli.Utils.UserError is gone with new structure. So we only have to deal with qx.tool.utils.Utils.UserError yet

**Comment by cboulanger** [comment]
Fixed with #437.
