### ISSUE TITLE
"externalResources" key in Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#411]
There seems to be some confusion about the location of the `externalResources` in Manifest.json: is it a property of `provides` or a top-level property? 

The documentation is inconsistent: 
a. In the [example](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/configuration/Manifest.md#reference), it is a top-level property.  All our templates treat it as a top-level property, and `qx add script` as well as the [compiler code](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/app/Library.js#L201) do so, too. 
b. In the [description](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/configuration/Manifest.md#description-of-keys) and in the [json schema](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/schema/v1/Manifest.json) it belongs to `provides`. It might make more sense to put it into the `provides` object, but this would break alot of people's code, unless we provide an automatic migration path.

How should we proceed? I have fixed the json schema in this branch: https://github.com/qooxdoo/qooxdoo-compiler/tree/cboulanger-apply-config-api . We could also allow both and document only b).

**Comment by hkollmann** [comment]
It's a top level property. It do not belong to provides. IHMO should stay where it's implementated.

**Comment by cboulanger** [comment]
Issue has been settled via #413. @johnspackman, could you update the documentation?

**Comment by johnspackman** [comment]
no problem, its on my list

**Comment by johnspackman** [comment]
oh wait a minute - isnt https://github.com/qooxdoo/qooxdoo-compiler/pull/414 it by @hkollmann ??

**Comment by hkollmann** [comment]
Yes it is

Von meinem iPad gesendet
