### ISSUE TITLE
Remove "provides.type" key in Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#415]
In the [documentation of Manifest.json](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/configuration/Manifest.md#description-of-keys), there is a `provides.type` key, which has no function and is not used by the compiler or the framework. 

I suggest we remove it completely from the documentation, the skeletons and mark it as deprecated in the json schema file.

**Comment by hkollmann** [comment]
Good idea. Is only used in the python toolchain. Could you make an PR?

**Comment by cboulanger** [comment]
I'll provide one eventually, it's not top priority....

**Comment by cboulanger** [comment]
Done
