### ISSUE TITLE
`qx package migrate` does not migrate eslint settings

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo-compiler#435]
When upgrading using `qx package migrate`, the eslint settings specified in compile.json were not changed from `qx/browser` to `@qooxdoo/qx/browser`

**Comment by cboulanger** [comment]
This issue bit me, too... needs a fix.

**Comment by hkollmann** [comment]
Done with https://github.com/qooxdoo/qooxdoo-compiler/pull/626
