### ISSUE TITLE
qxcompiler: allow JSDoc comments in the format used elsewhere (type *before* variable name)

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#446]
qooxdoo JSDoc comments are backwards from the rest of the world. Everyplace else, the type comes before the variable name; in qooxdoo, it's reverse. Suggest that the compiler allow recognizing it either way, so we could slowly migrate to the industry standard.

**Comment by cboulanger** [comment]
This should be fixed relatively soon because the APIViewer displays no parameter info if the correct jsdoc syntax is used.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo-compiler/pull/546
