### ISSUE TITLE
Resource Manager needs to compile directly into target (eg for SCSS)

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#47]
Please see https://github.com/qooxdoo/qooxdoo-cli/issues/44 for detailed explanation, but the short version is that SCSS needs to be compiled into target output resources, and not into the source resource directory.  Without a fix for this, `maker.make` has to be run twice, every time.

**Comment by cboulanger** [comment]
@hkollmann @johnspackman Still relevant? Something to be fixed before release or later?

**Comment by hkollmann** [comment]
We can fix it later. Only relevant for mobile apps

Von meinem iPad gesendet
