### ISSUE TITLE
Publish json-schema files at www.qooxdoo.org/schema or at purl.org

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#487]
`"$schema": "https://raw.githubusercontent.com/qooxdoo/qooxdoo-compiler/master/source/resource/qx/tool/schema/Manifest-1-0-0.json"` is not very pretty as a json-schema address, but also we might want to move the source files in the repo one day. It would be better to use a canonical address such as `www.qooxdoo.org/schema` (which requires publishing the files when deploying to the website) - or we use a persistent redirection service such as https://archive.org/services/purl/

**Comment by oetiker** [comment]
I would go for something below qooxdoo.org ... this is under our control

**Comment by cboulanger** [comment]
I don't know if you agree, but I think this is a "blocker" issue that should be fixed before release, once we have the new website ready. @oetiker Do you have an idea how we can configure the server to transparently serve the github raw file contents via the qooxdoo url?

**Comment by oetiker** [comment]
you can not do it transparently, BUT the files can be copied along with all the other stuff on deployment.

**Comment by cboulanger** [comment]
True..

**Comment by cboulanger** [comment]
Done
