### ISSUE TITLE
Mixin with environment dependent definition is not parsed

### ISSUE THREAD

**Issue by mbgonicus** [qooxdoo/qooxdoo-compiler#49]
We have a mixin which is defined similar to this:

```javascript
qx.Mixin.define("foo.MBar", qx.core.Environment.select("qx.baz", {
  "true" : { /* ... */ },
  "false" : { /* ... */ }
}));
```

It used to work with the old python generator, but with the new compiler the compilation is aborted with the message:
```
foo.MBar: Missing class definition - no call to qx.Class.define (or qx.Mixin.define etc)
ERROR: Cannot write application 'foo' because it has fatal errors
```

I traced it down to [ClassFile.js#L828](https://github.com/qooxdoo/qooxdoo-compiler/blob/bd3b4a80c720a16c1334dfdd5dcdfd773b0be234/lib/qxcompiler/ClassFile.js#L828):

```javascript
if (classDef.type != "ObjectExpression") {
  return;
}
```

As `classDef.type` is a `CallExpression`. 

A workaround would be to move this check below [ClassFile.js#L836](https://github.com/qooxdoo/qooxdoo-compiler/blob/bd3b4a80c720a16c1334dfdd5dcdfd773b0be234/lib/qxcompiler/ClassFile.js#L836):
```javascript
t.__foundClassDef = true;
```
This prevents the error and at least the compilation is not aborted. But of course the definition is not parsed and therefore not considered for dependencies, translations, etc.

I don't have enough understanding of the code base to fix this. But even without trying I'm sure it also effects Class and Interface definitions as well.

**Comment by mbgonicus** [comment]
It seems that the functionality is basicly there: [ClassFile.js#L938](https://github.com/qooxdoo/qooxdoo-compiler/blob/01f623113cba0bf8daf4e7b417e0e7568ff27819/lib/qxcompiler/ClassFile.js#L938)

But there is a todo comment. What exactly is there todo?

**Comment by johnspackman** [comment]
it's for code elimination - so if the call to `qx.core.Environment.select` can be determined at compile time, the code is modified to only have the code that will apply.  I've done it for `.get` but it looks like I forgot to go back and implement `.select`

**Comment by mbgonicus** [comment]
I don't really get it - the code for `.get` and `.select` seems to be identical. Does it work for `.get`?

**Comment by johnspackman** [comment]
You're right - somehow the code for code elimination has been, erm, eliminated!  I'll have to dig it out and reinstate it.
