### ISSUE TITLE
Translations (and locale) data to be loaded on demand

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#50]
Translations and locale data is currently copied into the application boot strap in `resources.js`, but while locale data is quite small the translations can be sizable.  The generator supported the option to load translations as parts via the `"i18n-as-parts" : true` config setting, there needs to be something similar in compiler

See https://github.com/qooxdoo/qooxdoo-cli/issues/56#issuecomment-348424403

**Comment by johnspackman** [comment]
See also https://github.com/qooxdoo/qooxdoo/issues/9419, maybe CLDR is no longer necessary

**Comment by cboulanger** [comment]
You decide which milestone this belongs to...
