### ISSUE TITLE
Redundant declaration of polyfill function in "build" target

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#502]
See http://www.qooxdoo.org/qxl.packagebrowser/qxl.packagebrowser/demos/ITISFoundation/qx-iconfont-fontawesome5/iconbrowser/part-0.js

The `function _typeof(e)` is declared multiple times in a row.

**Comment by johnspackman** [comment]
Im not seeing the repetition any more, the polyfill is loaded once - please can you confirm?

**Comment by cboulanger** [comment]
The original file does not exist any more - which is a problem that I need to fix (https://github.com/qooxdoo/qxl.packagebrowser/issues/2), so I cannot check. But I think we can close this and reopen should the problem show up again.
