### ISSUE TITLE
unresolved use of symbol errors

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#503]
The new ompiler throws a lot of Unresolved use of Symbol:

vzaweb.custom.smart.ui.dialogs.SelectHandZaehler: [17,30] Unresolved use of symbol activeUserOnly
legal      var {activeUserOnly = false} = aOptions;

vzaweb.core.MCookieHelpers: [208,37] Unresolved use of symbol encodeURI
legal function

qx.Promise: [6306,36] Unresolved use of symbol selfmise
          var globalObject = typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window :
              typeof global !== "undefined" ? global :
                this !== undefined ? this : null;

vzaweb.ui.AbstractPage: [384,21] Unresolved use of symbol decodeURI

vzaweb.ui.dialogs.ShowSVG: [435,29] Unresolved use of symbol FileReader
  legal

vzaweb.io.remote.CallExternals: [30,25] Unresolved use of symbol FormData
      var formData = new FormData();
   legal

vzaweb.ui.dialogs.EditSettings: [890,43] Unresolved use of symbol Blob

vzaweb.ui.form.SelectFahrzeugArten: [31,27] Unresolved use of symbol gezaehlteOnly
vzaweb.ui.form.SelectFahrzeugArten: [32,32] Unresolved use of symbol maxArtenSelectable

    var {artData, artenSets, gezaehlteOnly = true, maxArtenSelectable = 0} = optional;
    this.setSelectionMode("one");
    this.__artenList = artenList;
    this.__datenArt = artData;
    this.__artenSets = artenSets;
    this.__gezaehlteOnly = gezaehlteOnly;

qx.bom.client.Runtime: [47,17] Unresolved use of symbol Packages
   need a fix 

qx.bom.element.AnimationJs: [182,30] Unresolved use of symbol getComputedStyle
   need a fix

Most of them are legal syntax. qx lint do not Show this errors.

And they have not been there in old version.,

How can they be fixed?

**Comment by hkollmann** [comment]
Please try a qx compile in the qooxdoo folder. The errors in qx.* Namespace haven't been there before.

**Comment by hkollmann** [comment]
And please try a qx compile compileServer.json!

**Comment by johnspackman** [comment]
There are separate lists of allowed global symbols now, depending on whether the target support node, rhino, browsers, or a combination - we started talking about this [on gitter the other day](https://gitter.im/qooxdoo/qooxdoo-compiler?at=5d288be101621760bc9fc6ed)

The new unresolved detection is picking up a lot more things now (should be exhaustive) so there are some more that needed to be added to those lists (eg encodeURI, decodeURI, FileReader, FormData), plus there are a some `@ignore` that need to be added.

This one is a bug:

```
var {artData, artenSets, gezaehlteOnly = true, maxArtenSelectable = 0} = optional;
this.setSelectionMode("one");
```

These ones are bugs in Qooxdoo: 

```
qx.bom.client.Runtime: [47,17] Unresolved use of symbol Packages
qx.bom.element.AnimationJs: [182,30] Unresolved use of symbol getComputedStyle
```

> Most of them are legal syntax. 
Yes, but valid warnings

> qx lint do not Show this errors.
Apart from that object deconstruction pattern bug above, I think that's because `qx lint` has the same lax/wide scope of globals that we used to have.  It also only looks at the top level for library globals (eg qx.*, vzweb.* etc)

> And please try a qx compile compileServer.json!
I'm guessing you get loads, probably in Qooxdoo?  This is because when compiling just for node, only node globals are being allowed by default - which means that (for example) references to `window` will generate a warning in a pure-node target, and these need to be cleaned up now.

Please can you remind me where your repo is for `vzaweb.*`?  Or can you email me the code?  I'll work through it all and get back to you with a fix.

**Comment by hkollmann** [comment]
> These ones are bugs in Qooxdoo:
> qx.bom.client.Runtime: [47,17] Unresolved use of symbol Packages
> qx.bom.element.AnimationJs: [182,30] Unresolved use of symbol getComputedStyle

PR is in work!

**Comment by hkollmann** [comment]
What's about adding a globals entry to compile.json? There we can set e.g. window as global for mixed enviroments.

Like the undocumented - shame over me - ignores?

**Comment by hkollmann** [comment]
see Compile.js, 364:
         if (config.ignores) {
          analyser.setIgnores(config.ignores);
        }

**Comment by hkollmann** [comment]
I send you an email with the project

**Comment by hkollmann** [comment]
> I'm guessing you get loads, probably in Qooxdoo?  This is because when compiling just for node, only node globals are being allowed by default - which means that (for example) references to window will generate a warning in a pure-node target, and these need to be cleaned up now.

Then we have to clean up the whole qooxdoo Project 😄

**Comment by hkollmann** [comment]
And we have some stubs in the loader-server.tmpl.js to overcome the Problem of missing objects in node/rhino:

  window.document = document = {
      readyState: "ready",
      createEvent: function() {
        return {
          initCustomEvent: function() {}
        };
      },
      createElement: function () {
		  return {}
	  },
      addListener: function() {},
      removeListener: function() {},
      documentElement: {
        style: {}
      }
  };

  if (!this.window) 
    window = this;
  window.dispatchEvent = function() {};

  if (!window.navigator) window.navigator = {};
  if (!window.navigator.userAgent) {
    window.navigator.userAgent = "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; de-de) AppleWebKit/533.17.8 (KHTML, like Gecko) Version/5.0.1 Safari/533.17.8";
  }
  if (!window.navigator.product) window.navigator.product = "";
  if (!window.navigator.cpuClass) window.navigator.cpuClass = "";

**Comment by hkollmann** [comment]
So IMHO it would be legal to add window etc to node/Rhino globals.

**Comment by hkollmann** [comment]
BTW ignores is documented in the schema compile-1-0-0.json!

**Comment by johnspackman** [comment]
I agree with everything you've said above - I've added globals such as window and document into the "common" list and a few other tweaks; there are some changes in the framework which need to be updated, and the ones I've found are in https://github.com/qooxdoo/qooxdoo/pull/9756.  The code you sent me now compiles, but there wasn't a compileServer.json?

**Comment by hkollmann** [comment]
compileServer.json is part of qooxdoo Framework to compile the npm stuff.
