### ISSUE TITLE
main index.html disappear

### ISSUE THREAD

**Issue by rommni** [qooxdoo/qooxdoo-compiler#505]
I updated qooxdoo-compiler today, and since this update when i make a qx compile (build or source), the file:
`"my_app_path"/compiled/source(or build)/index.html` is not present
I have to go to:
`"my_app_path"/compiled/source(or build)/"my_app_name"/index.html `to access the app.

Current version of @qooxdoo/compiler: **_1.0.0-beta.20190724-0803_**
My last version where i haven't this bug: **_1.0.0-beta.20190715-1934_**

**Comment by cboulanger** [comment]
I can confirm that bug.
