### ISSUE TITLE
Build target seems to be broken

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo-compiler#51]
If I run
```
$ qx compile --target=build
SyntaxError: Unexpected token keyword «function», expected punc «,»ogo
    at JS_Parse_Error.get (eval at <anonymous> (/home/cajus/Projekte/cajus/new/qooxdoo-compiler/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at qxcli.commands.Compile.process.catch (/home/cajus/Projekte/cajus/new/qooxdoo-cli/lib/qxcli/commands/Compile.js:610:31)
    at <anonymous>
```
while the *source* target works fine. *ogo* looks like a cropped version of the applications name "nogo".

**Comment by johnspackman** [comment]
This is because you've checked out the latest github, but there are new modules which npm needs to download.  You need to `cd` to `qooxdoo-cli` and `npm i`; if you also have a checkout of `qooxdoo-compiler` you then also need to `npm link qxcompiler`

**Comment by johnspackman** [comment]
It looks like it's the same app that was in the tarball you sent me a short while ago?  I've just tried with that and can't reproduce it; please can you confirm that both copies of the repo are up to date and using the `npm link` to get compiler hooked into cli, then delete `db.json`, `resource-db.json`, and `build-output/` and try again?  If it still fails, please can you send me an updated tarball and I'll try again?

**Comment by cajus** [comment]
@johnspackman that's the same application, which is basically unchanged. I don't use a globally linked qx-cli/compiler. There's just qx-cli reference  in the *package.json*. Removing the *db.json files does not seem to help.

The playground itself doesn't work completely in the moment, because I'm playing around with *feathersjs* on the backend side. But while it's just a "build" issue, that doesn't matter, I guess.

Sending you the details via *gitter*.
