### ISSUE TITLE
QX compiler incorrectly transpiles this.base calls when they belong to patched methods

### ISSUE THREAD

**Issue by ronkie** [qooxdoo/qooxdoo-compiler#517]
Trying new qx compiler on an existing application gives the following issue.

In Application.js we have a couple of patches for qooxdoo code. For example:

qx.Class.patch(qx.ui.core.Widget, qx.Mixin.define("MInsets", {
                members: {
                    getInsets: function() {
                        if(this.getDecorator()) {
                            var decorator = qx.theme.manager.Decoration.getInstance().resolve(this.getDecorator());
                            if(decorator) {
                                return this.base(arguments);
                            }
                        }
...

When running this in the browser, we get the following exception:

Native.js? [sm]:58 018930 qx.ui.core.queue.Layout: Error in the 'Layout' queue:TypeError: Cannot read property 'main' of undefined TypeError: Cannot read property 'main' of undefined

Tracing it back to the transpiled code shows this:

qx.Class.patch(qx.ui.core.Widget, qx.Mixin.define("MInsets", {
                    members: {
                        getInsets: function getInsets() {
                            if (this.getDecorator()) {
                                var decorator = qx.theme.manager.Decoration.getInstance().resolve(this.getDecorator());
                                if (decorator) {
                                    return ajaxclient.Application.$$members.main.base.call(this);
                                }
                            }
...

So, a this.base call is transpiled in this case as if it would belong to Application.main method, while it belongs to Widget.getInsets method.

**Comment by hkollmann** [comment]
Test is here https://github.com/qooxdoo/qooxdoo-compiler/pull/624
