### ISSUE TITLE
source code formating

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#522]
From https://github.com/qooxdoo/qxl.apiviewer/issues/16

> @oetiker I like adding little examples to my qooxdoo class jsdoc:
https://github.com/oposs/headerpuppet/blob/master/source/class/headerpuppet/HeaderPuppet.js#L20
when using `<pre class="code">` indentation does not work

**Comment by hkollmann** [comment]
fixed with #523
