### ISSUE TITLE
qx pkg upgrade overwrites @XXX releases

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#535]
When encountering a package that doesn't have a `vX.Y.Z` version, `qx pkg upgrade` should not overwrite this version with the latest compatible release, unless a flag (probably `--force`) is set.

**Comment by cboulanger** [comment]
this is already possible with the `--releases-only` option (I had forgotten about that!).
But: maybe this option should be true by default? @hkollmann @johnspackman, what would be your expectation: that versions that are pinned to a commit hash a) should be automatically upgraded by default, or b) that they should be left alone? My feeling is b)

**Comment by hkollmann** [comment]
B)
And true as default for realeses-only. We should have the same default behavior as with install

Von meinem iPad gesendet

**Comment by johnspackman** [comment]
👍 option B

**Comment by cboulanger** [comment]
Ok, I'll integrate this into #536
