### ISSUE TITLE
Travis tests should run with all supported node versions

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#548]
Currently, travis will use the latest node version to run the tests (ATM, that is v11). Instead, we should define all node versions that we officially support and then run the tests with all of them.

**Comment by hkollmann** [comment]
And we should add a windows test too

**Comment by hkollmann** [comment]
Wich node versions we do support?

- [ ] 8
- [ ] 10
- [ ] 12

**Comment by hkollmann** [comment]
Btw windows travis support is working. 
Only test-deps.js fails in windows

**Comment by hkollmann** [comment]
Do we need tests for macos too?

**Comment by cboulanger** [comment]
MacOS is the same as Linux but sometimes the command library versions differ (for example, MacOS has CoreUtils v8.30, which supports parameterized shebangs, while the Distro used by Travis only has an older version of the CoreUtils Library. So we could add separate MacOS tests, but I don't think they are absolutely necessary.

**Comment by johnspackman** [comment]
10, 11, and 12 are mandatory, surely? Bevaus4 10 is LTS.

But if we can pass the tests on 8 without major issues, it could be a nice to have - even if only to let people know what works. A big "use 8 at your own risk" warning would be appropriate though.

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo-compiler/pull/562
