### ISSUE TITLE
qooxdoo.d.ts file will cause compiler to die horribly ...

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#568]
# how to reproduce

```
$ touch source/class/myapp/qooxdoo.d.ts
```
in compile.json add

```
"include": [ "myapp.*"]
```

now try to compile ...

**Comment by johnspackman** [comment]
why would you put the `qooxdoo.d.ts` inside your source directory??  It's a definition file intended for visual studio to read, it's not intended to be recompiled by the compiler.

**Comment by oetiker** [comment]
it was an accident :)

**Comment by oetiker** [comment]
but the effect is pretty dramatic

**Comment by johnspackman** [comment]
aha :)

**Comment by oetiker** [comment]
I guess the problem comes from the way the compiler turns x.y.z into a file and folder name

**Comment by hkollmann** [comment]
qooxdoo.d.ts can not be resolved to an correct classname.

**Comment by oetiker** [comment]
and the compiler dies trying ... with a less than helpful error message

**Comment by cboulanger** [comment]
Since this is a highly irregular situation, I don't think we should (at least right now) spend time accomodating it. Closing this. Feel free to reopen if you find it necessary.

**Comment by oetiker** [comment]
the problem at the heart of this is that the rules the compiler applies to filenames are too loose ... I literally spent hours figuring out why the compiler just dies ... if it issued a warning, fine, but just killing itself, is no way to go I would say.

**Comment by oetiker** [comment]
have you tried ? and looked at the effect ?

**Comment by cboulanger** [comment]
I haven't. Maybe you could make a PR adding a simple check to the compiler to skip `*.d.ts` files? @johnspackman could point you to where it must be placed?

**Comment by johnspackman** [comment]
`qx.tool.compiler.app.Library.scanForClasses` https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/app/Library.js#L234-L321

**Comment by oetiker** [comment]
> I haven't. Maybe you could make a PR adding a simple check to the compiler to skip `*.d.ts` files? @johnspackman could point you to where it must be placed?

:) it is not about d.ts files ... it is about the way the compiler converts file names into classes ... which makes assumptions that are not true ... in my book, code that scans the file system MUST not crash while doing so regardless of the files it finds ...

**Comment by oetiker** [comment]
unfortunately I am not at all familiar with the compiler code, but I do care about it working reliably so I have assigned this to myself and will see if I can figure out for to make it stable ...
