### ISSUE TITLE
"Unresolved use of symbol" warning, externalResources/script function

### ISSUE THREAD

**Issue by rommni** [qooxdoo/qooxdoo-compiler#583]
Like discussed on gitter, it could be an interesting feature to avoid  "Unresolved use of symbol" warning, for function declared in a plain javascript file defined in externalResource (or maybe elsewhere don't mind to give your opinion).

Just to expose the problem it solves, currently i have a plain javascript file with plenty "utility" function, i declared it in Manifest.json externalResource/script, i used these functions in many qooxdoo classes, it works without problem but the compiler throw a  "Unresolved use of symbol" warning for each use of function. The problem can be solved by adding on each class a @ignore for each function but it's quite time-consuming when you have like me many functions and many classes. The goal is so to automaticaly avoid these warning.

**Comment by hkollmann** [comment]
There is a global ignores for this purpose - only documented here:
https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/schema/compile-1-0-0.json

    "ignores": {
      "description": "An array of names which the compiler should ignore. Same as @ignore in source code",
      "type": "array",
      "uniqueItems": true,
      "examples": [
        "modules.*"
      ],
      "items": {
        "type": "string"
      }
    },

**Comment by hkollmann** [comment]
We should add a section to https://github.com/qooxdoo/qooxdoo/blob/master/docs/compiler/configuration/compile.md.

SASS Option is missing to in compile.md

**Comment by rommni** [comment]
Thanks @hkollmann  for the information, i will use that, however, I have no idea of how difficult it can be and what part of code handle that but i think it could still be a good idea, if possible, to ignore by default function (or other things) declared as external script.

And yes an update of docs about that will be necessary ;)

**Comment by oetiker** [comment]
three cheers for the schema :)
