### ISSUE TITLE
Node crash on qx compile (cause unknown) and work-around

### ISSUE THREAD

**Issue by reedspool** [qooxdoo/qooxdoo-compiler#585]
Just experienced a crash.

Version: 
```
$ node_modules/@qooxdoo/compiler/qx --version
1.0.0-beta.20190924-0742
```

Crash report (with stuff redcated):
```
$ node_modules/@qooxdoo/compiler/qx compile --target=build
Cannot find path source/resource required by library [Redacted: Our project specific library]
Warning: File source/index.html exists but is no longer used
[                  ] - Compiling
<--- Last few GCs --->

[2009:0x354c9a0]    15786 ms: Mark-sweep 1397.1 (1419.1) -> 1397.1 (1420.1) MB, 1297.6 / 0.0 ms  (average mu = 0.061, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xe507d0dbe1d]
    1: StubFrame [pc: 0xe507d0dd1df]
Security context: 0x08e9b6a9e6e9 <JSObject>
    2: parseString [0x1ae64ba51041] [path/to/my/node_modules/@qooxdoo/compiler/source/class/qx/tool/utils/json/Tokenizer.js:~401] [pc=0xe507d5c8940](this=0x28e3861af7a1 <JSFunction wrapper (sfi = 0x182bd937e231)>,input=0x0fb3ccb82201 <Very long string[537475201]>,index=19828278,l...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa0c0 node::Abort() [path/to/my/node_m]
 2: 0x8fa10c  [path/to/my/node_m]
 3: 0xb0026e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [path/to/my/node_m]
 4: 0xb004a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [path/to/my/node_m]
 5: 0xef49b2  [path/to/my/node_m]
 6: 0xef4ab8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [path/to/my/node_m]
 7: 0xf00b92 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [path/to/my/node_m]
 8: 0xf014c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [path/to/my/node_m]
 9: 0xf04131 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [path/to/my/node_m]
10: 0xecd5b4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [path/to/my/node_m]
11: 0x116d73e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [path/to/my/node_m]
12: 0xe507d0dbe1d
```

compile.json (with stuff redacted)
```
{
  "targets": [
    {
      "type": "source",
      "outputPath": "output/source",
      "addCreatedAt": true
    },
    {
      "type": "hybrid",
      "outputPath": "output/hybrid"
    },
    {
      "type": "build",
      "outputPath": "build",
      "minify": "mangle",
//    "minify":"off",
      "addCreatedAt": true
    }
  ],
  "defaultTarget": "source",
  "locales": [
    "en"
  ],
  "environment": {
    "APPLICATION": "redacted",
    "QOOXDOO_PATH": "../library/qooxdoo.git",
    "QXTHEME": "redacted.theme.Theme",
    "API_EXCLUDE": [
      "qx.test.*",
      "${APPLICATION}.theme.*",
      "${APPLICATION}.test.*"
    ],
    "LOCALES": [
      "en",
      "pt"
    ],
    "CACHE": "${TMPDIR}/qx${QOOXDOO_VERSION}/cache",
    "ROOT": ".",
    "qx.icontheme": "Oxygen"
  },
  "applications": [
    {
      "class": "redacted.Application",
      "theme": "redacted.theme.Theme",
      "name": "script",
      "bootPath": "./boot"
    }
  ],
  "libraries": [
    "../library/qooxdoo.git/framework",
    "../library/collapsablepanel.git",
    "../library/dialog.git",
    "../library/RedactedTheme.git",
    "../library/uploadmgr.git",
    "../library/mlaif.git",
    "."
  ],
  "$schema": "https://raw.githubusercontent.com/qooxdoo/qooxdoo-compiler/master/source/resource/qx/tool/schema/compile-1-0-0.json"
}
```

Successful work-around was `rm -rf ./build`, which is this target's `"outputPath"`. Crash has not occurred again but will report here if it recurs.

A temporary workaround, included here for completeness, was to add a node flag to add more memory. This worked once then failed (even after doubling the number a few times):

```
node --max-old-space-size=4096 node_modules/@qooxdoo/compiler/qx compile --target=build
```

**Comment by derrell** [comment]
After discussing this, it turns out that we've had separate occurrences of this with two different developers.

**Comment by hkollmann** [comment]
Which system are you using?

**Comment by reedspool** [comment]
Ubuntu 18.04

```
$ node -v
v10.16.3
```

Let me know any other details that would be helpful.

**Comment by johnspackman** [comment]
IMH this is a node-specific issue and not the compiler - but taking a guess at the dump I'd agree that it's memory related.  I had to use `--max-old-space-size=8192` on node v8 and v10 for my projects.

**Comment by hkollmann** [comment]
Could you try node 12?

**Comment by derrell** [comment]
@reedspool works with me. This is not an incredibly huge project that he's working on; there are only about 50 classes within the project (in addition to what qooxdoo brings in). If memory is exhausted compiling this project, I suspect we'll see problems from many users, so shouldn't just pass it off as a node problem.

And although we can try node 12, node 10 is still the recommended LTS version, and we may not be ready to upgrade to 12.

**Comment by hkollmann** [comment]
Node 12 has reached LTS state: https://nodejs.org/en/about/releases/

**Comment by reedspool** [comment]
@hkollmann We cannot repro. After the posted workaround, the issue has not recurred. When it does recur we will do more experiments including trying v12

**Comment by reedspool** [comment]
We've isolated this issue and can reproduce it consistently in our code base (although we have not yet tried to make a small example).

The issue occurs in the constructed db.json file when using a build target. In our project, this file grows with each `qx compile --target=build` without the source code changing at all. After deleting the file and compiling with that command, the file sat around 500,000 bytes. After running it for a while, like so...:

```bash
while true; do
  time node_modules/@qooxdoo/compiler/qx compile --target=build;
  ls -la build/db.json; # Display the file size
done;
```

... the crash occurred when the file sat around 31,000,000 bytes. This didn't take very long. I think if we checked further we'd find it growing geometrically or exponentially. If more concrete data is needed, we can run the above experiment again and analyze the results.

Looking at the contents of the db.json file, we found one source of exponential growth, but checking the file size between successive compilations we do not believe the following bug is the sole cause of the file growth.

The cause we found was that escape slashes in translation strings were being re-escaped on each compilation. The next compilation, those two slashes would themselves be escaped and so on. E.g. `this.tr("Call me \"%1\"", name);`, in the db.json this entry would look like this after some number of compilations: ``

```
"translations": [
{
  "msgid": "Call me \\\\\\\\\\\\\\\"%1\\\\\\\\\\\\\\\"",
  "lineNo": 94
},
```

Again, we don't believe this accounts for all the growth in the db.json, but we were unable to find the rest of it at first glance.

**Comment by reedspool** [comment]
Thanks for your quick work on this @johnspackman and @hkollmann. Can you speak to the other cause of the growth other than the string escapes?

**Comment by johnspackman** [comment]
@reedspool no worries; this was the only cause of db.json increasing file size that I found, please can you delete your target output directory and then try again?  If you're still getting growth, you should be able to use a text base compare with before & after versions of db.json and narrow down a reproducable test case quite quickly
