### ISSUE TITLE
"libraries" issue (was: adding empty "libraries" array in compile.json breaks compilation)

### ISSUE THREAD

**Issue by valette** [qooxdoo/qooxdoo-compiler#596]
Hi,
adding this line:
`"libraries" : [],`
to compile.json breaks compilation. My setup : 
```bash
$ qx --version
1.0.0-beta.20191105-1146
```

simple steps to reproduce:
```bash
$ qx create test
$ cd test
$ qx compile
... add "libraries" : [], to compile.json
$ qx compile
Cannot find class file test.Application
Cannot find class file test.theme.Theme
ERROR: Cannot find required library test
ERROR: Cannot find library required to create application for test.Application
```
is using the "libraries" field still possible for local libraries?

**Comment by hkollmann** [comment]
Yes of course it is.
Here is an working example:
    "libraries": [
        "../vzacore",
        "."
    ],

**Comment by cboulanger** [comment]
We should update [the schema](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/resource/qx/tool/schema/compile-1-0-0.json#L226) to disallow an empty libraries array.

**Comment by hkollmann** [comment]
👍

**Comment by valette** [comment]
actually, adding a dummy library also seems to break compilation:

```bash
$ qx create test
$ qx create testLib
$ cd test
$ qx compile
... add "libraries" : [ "../testLib" ], to compile.json
$ qx compile
Cannot find class file test.Application
Cannot find class file test.theme.Theme
ERROR: Cannot find required library test
ERROR: Cannot find library required to create application for test.Application
```

note that I am actually using npx to execute qx

**Comment by hkollmann** [comment]
If you add libraries you have to add your current project with .
This is not done automatically if using libraries.

**Comment by valette** [comment]
ah sorry I forgot that... Closing the issue
