### ISSUE TITLE
node-sass  not working with node 13

### ISSUE THREAD

**Issue by fprijate** [qooxdoo/qooxdoo-compiler#602]
**Describe the bug**
node-sass@4.12.0 doesn't work with node 13

Please upgrade to node-sass@4.13.0

**Comment by cboulanger** [comment]
Transferred issue to the correct repo.

Can you provide a PR - just change [this line](https://github.com/qooxdoo/qooxdoo-compiler/blob/master/package.json#L78)

**Comment by hkollmann** [comment]
https://github.com/qooxdoo/qooxdoo-compiler/issues/376

**Comment by hkollmann** [comment]
fixed with https://github.com/qooxdoo/qooxdoo-compiler/pull/607
