### ISSUE TITLE
Have to separately install eslint-plugin-qx-rules to be able to run qx lint

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo-compiler#605]
After installing qx compiler on a fresh machine and try to lint via `qx lint`,  I find that I had to `npm i -g eslint-plugin-qx-rules` before the linting will work. This should be installed along with the compiler.

**Comment by hkollmann** [comment]
How did you install the compiler? Wich version? The new used Plugin  is @qooxdoo/eslint-plugin-qx which is mentioned in package.json of the compiler.

Did you test with a Fresh generated project?

**Comment by rad-pat** [comment]
Sorry, I found the problem - we had a .eslintrc checked into the repo with the section
 `  "plugins": [
    "qx-rules"
  ]`
