### ISSUE TITLE
Translations with msgids containing escaped quotes cause invalid entries in po files

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo-compiler#619]
When generating po files for our application I noticed some entries similar to:

It seems that the generation process does not like strings with escaped double quotes and will cause generation of invalid entries upon recompilation.

Steps to reproduce

Create a minimal app.
Wrap a string in `this.tr()` and add some escaped quotes e.g.
```
var button1 = new qx.ui.form.Button(this.tr("Click me \"here\""), "app8/test.png");
```
Compile the app once with `-u true`, see the correct entry generated in en.po:
```
#: testapp/Application.js
msgid "Click me \"here\""
msgstr "
```
Compile the app again with `-u true`, see the original entry marked unused and an additional invalid entry generated:
```
#. NO LONGER USED
msgid "Click me \"here\""
msgstr ""

#: testapp/Application.js
msgid "Click me \\"here\\""
msgstr ""
```

Expected result:
Only one valid entry to be generated

Actual result:
Repeated compilation adds more and more invalid entries to the po files

Tested with qx compiler 1.0.0-beta.20200228-1557, nodeJS v10.16.3 on Ubuntu 18.04.4

**Comment by johnspackman** [comment]
@rad-pat @oetiker Please can you retest when https://github.com/qooxdoo/qooxdoo-compiler/pull/622 is merged?

**Comment by rad-pat** [comment]
@johnspackman, the problems appear to be fixed as far as I can see so I'll close the issue if @oetiker is satisfied too.
