### ISSUE TITLE
More control over boot script injection

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo-compiler#62]
If you've built for variants or deal with certain broken browsers, you want to control how (or which) script is injected into the template `boot/index.html`.

Currently there's no way to i.e. load the script via `boot.js?42` to trick a broken caching mechanism. Or even load a variant `boot-webkit.js` instead. Where the variant type is detected via JS on load time.

**Comment by cboulanger** [comment]
@johnspackman Does this still hold true? If yes, @cajus, is it still a relevant problem for you or one that can be addressed later?

**Comment by johnspackman** [comment]
This is solved in that the `source/boot/index.html` can be used to provide a custom index.html; that .html file could (for example) inject it's own `<script>` tag to load `boot.js`, and so can add `boot.js?1234` or perform any other kind of dynamic changes.
