### ISSUE TITLE
Remove message "X is not a vaild key. Please see the API-doc of qx.core.Environment for a list of predefined keys." for custom environment variables

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#630]
The `qx.core.Environment` API is very useful to create your own application environment variables, but it is confusing for beginners and annoying for the others that the compiler outputs this message each time when you use your custom environment variable name which hasn't been defined by the framework itself. 

Instead, I would find it useful if the compiler collected a list of the names used used and saved it somewhere. This would enable to integrate this information into the documentation later. I assume the original idea of the warning was to alert users that they had a typo in the name. This could be better implemented by comparing the list of names in between compiler runs, and output an information which new names have been added to the list. This would make it easy to spot mistakes.

**Comment by cboulanger** [comment]
Alternatively, we could use a custom jsdoc tag to declare the environment variable explicitly (`@env myapp.do.stuff This is the documentation for the variable`), and only output the warning if the name is not being declared. This would have the additional advantage that the APIViewer could display it.

**Comment by johnspackman** [comment]
AIUI this only appears if the key is not formed properly - but the message is poor because it suggests that there is a master list in Environment, but you are supposed to be able to define keys in a class and have it be valid.  Really, the message is saying that it cannot find a default value for that setting, whether in `qx.core.Environment`, a class, or a compiler/generator setting

**Comment by derrell** [comment]
I had a related issue, where I wanted to compile out a bunch of code if it wasn't explicitly requested. I therefore defined it in the `environment` key in compile.json, as value `false`... and then if a value was specified for it with `--set-env`, it was a known "variable" name. It's not awful this way, and in fact, allows defining what the allowable (referenced) environment variables area. I'm not convinced it's wrong either way (expecting it to be defined, or not caring whether it's defined).

**Comment by cboulanger** [comment]
What about fixing the error message and limiting it to `--verbose` mode? This would eliminate the warnings for code that one does not have control over (such as external libraries) but you can still get the message if you want. This would be a quick and easy fix.

**Comment by cboulanger** [comment]
This is closely related to https://github.com/qooxdoo/qooxdoo/issues/9832 - fixing this in a systematic way seems to require more thought & effort than we should/can invest before release. Probably changing the error message and suppressing it unless in verbose mode will be enough for now. I will supply a PR.

**Comment by cboulanger** [comment]
Done with https://github.com/qooxdoo/qooxdoo/pull/9910
