### ISSUE TITLE
this.getCompilerApi().getCommand() do not return the current command

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo-compiler#643]
With your last commit all of the compile.js files in different projects do not run any longer.
Problem is this code:
```
   let command = this.getCompilerApi().getCommand();
  command.addListener("made", this.__onMade, this);
```
In the old version command was the actual used command derived from qx.tool.cli.commands.Command.
In the new version it's qx.tool.cli.Cli not the current command. So adding listeners will not work.
Any idea how to solve this?

**Comment by hkollmann** [comment]
None of the event based compile.js are working any longer

**Comment by cboulanger** [comment]
Question is if we should revert the last commit or if @johnspackman can provide a quick fix?

**Comment by johnspackman** [comment]
hmm, I havn't looked at the code but I suspect that this is an issue because compile.js is now loaded *before* a command is determined.  Where can I see this - is this apiviewer?

**Comment by hkollmann** [comment]
This example is package browser. Apiviewer has the same problem.
And you are right - load is called before command is ready.
IMHO we need a second call during the command creating phase
