### ISSUE TITLE
SASS compilation problem in mobile app

### ISSUE THREAD

**Issue by eda2z** [qooxdoo/qooxdoo-compiler#655]
This may have been covered in another issue but I'm not sure. If I create a new mobile app and compile it I get the DEPRECATED message "Using the Qooxdoo v5 style of SASS Compilation; this is backwards compatible but the default will change in v7 to use the new style (see https://git.io/JegIS for details, and how to disable this warning)." If I run the app the fonts look all wrong. Please see my previous issue #247 from Dec 24, 2018. The fonts look identical to the fonts in that issue. What is also strange is if I take an existing mobile app, run qx clean followed by qx compile the resulting app looks fine? Am I missing something?

**Comment by johnspackman** [comment]
Please can you try adding this to your brand new app's `compile.json` :

```
  sass: {
    "compiler": "latest"
  }
```

if that doesn't fix it, please can you document the exact steps needed to reproduce it?

BTW that link is broken, I've just changed the code to what it should be (which is https://git.io/JfTPV or http://www.qooxdoo.org/docs/#/development/compiler/internals/Sass)

**Comment by hkollmann** [comment]
The newly generated app needs
sass: {
    "compiler": "compatible"
  }

The qooxdoo sass files are not reworked yet

**Comment by johnspackman** [comment]
`"compatible"` should be the default, so @eda2z please can you try both versions (but use `rm -rf compiled` before each attempt) and let us know how you get on

**Comment by hkollmann** [comment]
The warning is generated if no setting is there and the default is used,

**Comment by eda2z** [comment]
Here are all of the gory details - some should have probably been mentioned in the beginning. I am running the latest Arch linux, node v10.20.0, qx version 1.0.0-beta.20200421-0852, and sass 3.7.4-2 (this could very well be the problem?) and apache 2.4.43-1. I then execute the following:

qx create mobtest -t mobile -I
cd mobtest
qx compile

if I access mobtest/compiled/source/index.html from google chrome I see the login screen but the fonts are all wrong -- just like in issue #247.

Next I execute rm -rf compiled, and add "sass": {"compiler": "latest"} to compile.json.
Executing qx compile results in the following messages:

Cannot find library for mobtest/css/custom.cssx.bom.webfonts.Validator
Cannot find library for mobtest/css/custom.cssWriting Application mobtest
ERROR: Cannot find CSS resource: mobtest/css/custom.css
Error status 1 in mobtest/scss/custom.scss[1,1]: File to import not found or unreadable: source/resource/mobtest/scss/common/all.

Accessing mobtest/compiled/source/index.html from google chrome shows the same login screen.

Next I execute rm -rf compiled, and add "sass": {"compiler": "compatible"} to compile.json. Executing qx compile results in the following messages:

Error: Error: Error validating data for compile.json: 1) /sass/compiler: pattern should match pattern "^(legacy|latest)$"
    at wrapper._validateData (/home/ed/.nvm/versions/node/v10.20.0/lib/node_modules/@qooxdoo/compiler/source/class/qx/tool/config/Abstract.js:176:17)
    at wrapper.set (eval at __installFunctionFromCode (/home/ed/.nvm/versions/node/v10.20.0/lib/node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/framework/lib/qx_server/part-0.js:14914:36), <anonymous>:3:332)
    at wrapper.eval [as $$setDataImpl] (eval at __installFunctionFromCode (/home/ed/.nvm/versions/node/v10.20.0/lib/node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/framework/lib/qx_server/part-0.js:14914:36), <anonymous>:6:273)
    at wrapper.eval [as setData] (eval at __installFunctionFromCode (/home/ed/.nvm/versions/node/v10.20.0/lib/node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/framework/lib/qx_server/part-0.js:14914:36), <anonymous>:3:20)
    at wrapper.load (/home/ed/.nvm/versions/node/v10.20.0/lib/node_modules/@qooxdoo/compiler/source/class/qx/tool/config/Abstract.js:302:12)

No compiled directory is created.

I noticed several issues relating to different "types" of sass. Should I try different ones? I only have ruby-sass installed since it was required by another package. Thanks.

**Comment by johnspackman** [comment]
the sass we use is built in (it's node-sass) so it's not down to your version; thanks for the test case, i'll try it here

**Comment by eda2z** [comment]
I have to change some of my original comment. If I take a mobile app that has been working for a while and run it through qx clean followed by qx compile, I get the lackluster fonts. If I look in the chrome debugger is see a 404 error on

GET http://spike/qx6/mobiletodo/compiled/build/mobiletodo/mobiletodo:mobiletodo/css/custom.css net::ERR_ABORTED 404 (Not Found)

spike is the name of my server and qx6 is the document root. If the path instead read spike/qx6/mobiletodo/compiled/build/resource/mobiletodo/css then it would find the file. It looks like the middle of the path got trampled.

**Comment by eda2z** [comment]
I just updated to the latest version of the compiler today (1.0.0-beta.20200422-1126) and all of my mobile apps now look great. Thanks for the quick response.
