### ISSUE TITLE
font icons not working any more

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo-compiler#675]
one of the latest compiler updates broke the font icon support. It seems as if the glyphs for the font are not generated anymore. I do not find any resources for the font except the font files itself.

**Comment by oetiker** [comment]
just found this as well :( going to downgrade the compiler for now ...

**Comment by peuter** [comment]
I did some further testing. The last working version for me is `1.0.0-beta.20200415-0654`.
`1.0.0-beta.20200420-2025` and `1.0.0-beta.20200421-0852` do not compile at all in my ptroject so I can't test them and in `1.0.0-beta.20200422-1126` the font icons are broken.

**Comment by johnspackman** [comment]
i think i've just fixed it in https://github.com/qooxdoo/qooxdoo-compiler/pull/678
