### ISSUE TITLE
Include favicon in generated index.html

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#70]
Now that qooxdoo has a [cool new favicon](http://qx.surge.sh/Q/assets/favicon.png), we should use it in the application skeletons and provide automated way to include it in the compiled apps.

https://en.wikipedia.org/wiki/Favicon

**Comment by cajus** [comment]
Add 'mask-icon' additionally, to have website pinning in safari:

```
  <link rel="shortcut icon" type="image/png" href="favicon.png">
  <link rel="mask-icon" href="favicon.png" />
```

**Comment by johnspackman** [comment]
closed because merged PR
