### ISSUE TITLE
Remove "qx contrib" as an alias of "qx package"

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#713]
We left `qx contrib` as a backward-compatibility alias when we changed to `qx package`, however, at this point, the alias is no longer necessary, as nobody still uses `qx contrib`. 

I think it is confusing to have two aliases of `qx package`, i.e. `qx pkg`  and `qx contrib`, so `qx contrib` should be removed.

**Comment by hkollmann** [comment]
Done in https://github.com/qooxdoo/qooxdoo-compiler/pull/709
