### ISSUE TITLE
Resource manager needs to pool, instead of opening unlimited number of images

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#725]
Compiling a big application will run into MacOS's limit on concurrently open files.

**Comment by johnspackman** [comment]
@cboulanger please can you confirm that this exists?  There is already a pool implemented at https://github.com/qooxdoo/qooxdoo-compiler/blob/master/source/class/qx/tool/compiler/resources/Manager.js#L274 which looks like it protects against loading more than 10 images at a time

**Comment by cboulanger** [comment]
I don't see any problems any more! Thank you. Closing the issue.
