### ISSUE TITLE
Unresolved use of symbol with array rest operator

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#726]
Using the testtapper package, one gets repeated `Unresolved use of symbol testName.join` warnings when compiling. The compiler complains about [these lines](https://github.com/qooxdoo/qxl.testtapper/blob/master/source/class/qxl/testtapper/Application.js#L200-L201):
```javascript
let [testClass, ...testName] = test.split(":");
this.addTreeItem("not ok",that._cnt, testClass, testName.join(""), message);
```
which means it does not recognize yet the `...testName` syntax.

**Comment by hkollmann** [comment]
test_3: function ({param1, param2} = {}) {
        console.log(param1, param2);
      }

is not working either

**Comment by hkollmann** [comment]
fixed with https://github.com/qooxdoo/qooxdoo-compiler/pull/764
