### ISSUE TITLE
Reference Error : xxx is not defined for object declared in external resources

### ISSUE THREAD

**Issue by rommni** [qooxdoo/qooxdoo-compiler#729]
Since commit https://github.com/qooxdoo/qooxdoo-compiler/pull/654 (I tried to install qooxdoo-compiler with version 1.0.0-beta.20200415-0654 and 1.0.0-beta.20200420-2025 and the bug only appears since the second one) all the object i declared in external resources are not recognized by my application and so it doesn't work at all.

This problem only appears in Build Target not in Source Target.

My external resources are javascript libraries placed in folder source/resource/script/, and declared in Manifest.json in "externalResources"/"script", with this path : "script/mylib.js"

Don't mind to ask more details if it can help you.

**Comment by cboulanger** [comment]
Does it work if you declare the asset  with `@asset(script/*)` in the header comment of the class where the script is used?

**Comment by rommni** [comment]
I tried with @asset(script/*) in the main class of my application, however i didn't tried in the class were i'm using the script

**Comment by rommni** [comment]
I just tested to add @asset(script/*) in all the files where my libs are used but it doesn't change anything always the same error.

**Comment by hkollmann** [comment]
I use the same construct in my manifest.json. Everything is working. Could you have a look into your index.js if you found an urisBefore array with your external files in it?

**Comment by rommni** [comment]
The urisBefore seems to be defined in index.js however i still have an undefined reference when i use the object declare in the files:
 `` urisBefore:["../resource/script/mylib1.js","../resource/script/mylib2.js"]``

**Comment by hkollmann** [comment]
Are they loaded in index.js?

**Comment by rommni** [comment]
How can i see that? should the entire files be in index.js?

**Comment by hkollmann** [comment]
No the external files are loaded here:

  init: function(){
    var l = qx.$$loader;
    l.decodeUris(l.cssBefore, "resourceUri").forEach(function(uri) {
      loadCss(uri);
    });
    allScripts = l.decodeUris(l.urisBefore, "resourceUri");
    if (!l.bootIsInline) {
      l.parts[l.boot].forEach(function(pkg) {
        var add = l.decodeUris(l.packages[pkg].uris);
        Array.prototype.push.apply(allScripts, add);
      });
    }

**Comment by rommni** [comment]
Hum it seems to be ok, i have the same code of you, when i try in dev console to make the decodeUris and then i looked at the result it is a correct array of all my script path (i try to put the path in my web browser and i see correctly the code of my lib), however i don't know if there is a better way to check if the code is loaded.

**Comment by rommni** [comment]
However the scripts are not included in the head of my page, and when i run manually the commands (decodeUris then loadScript) the files appears in head of the page (don't know how it is supposed to be in normal way)

**Comment by hkollmann** [comment]
loading is done here

function loadScript(uri, callback) {
  var elem = document.createElement("script");
  elem.charset = "utf-8";
  elem.src = uri;
  elem.onreadystatechange = elem.onload = function() {
    if (!this.readyState || readyStateValue[this.readyState]) {
      elem.onreadystatechange = elem.onload = null;
      if (typeof callback === "function") {
        callback();
      }
    }
  };

**Comment by hkollmann** [comment]
And they are shown:
![image](https://user-images.githubusercontent.com/1053029/86573516-c88cbe80-bf74-11ea-9acc-d57f397149e8.png)

**Comment by rommni** [comment]
On my project, i have only the (index) and index.js, all the script doesn't appear (since the update). (They appeared when i run qx.$$loader.init() manually from the console (with an error however it think it's only because it's not a normal way to use it).

**Comment by rommni** [comment]
However i'm trying to reproduce the bug in a sample app and can't manage to do it, i have to try what part of my apps provoke the bug.

**Comment by rommni** [comment]
A sample app with the bug if needed : https://github.com/rommni/testScriptIncludeQooxdoo
Just clone it and do npx qx serve --target build to see the bug.
(If you do npx qx serve the app works)

**Comment by hkollmann** [comment]
Found the problem:
With build target all of your own code is merged in one big javascript file index.js. 
You try to load your TestScript direct in the init section of your property nameTest. This is done during file loading.
Loading of your own script is done later.

So you have 2 possibilities:
    - put loading of TestScript into your class constructor.
    - change your index.html in boot dir so that your own script is loaded before index.js. Using externalResources/script is not working in this case.

The whole thing works in source because there each class file is loaded seperately.

**Comment by rommni** [comment]
ok so if i understand well the externalResources shouldn't be used in the init of qooxdoo properties? 

Will try to change my code accordingly, thank you for your investigation.

**Comment by hkollmann** [comment]
Yep

**Comment by hkollmann** [comment]
@rommni : Can we close this issue?

**Comment by rommni** [comment]
Yep thank you I found an other way to write my code which solve the issue
