### ISSUE TITLE
when doing a compile I get There is no reference to index.js script in the index.html

### ISSUE THREAD

**Issue by hcarsten** [qooxdoo/qooxdoo-compiler#731]
There is no reference to index.js script in the index.html copied from [folder]/source/boot/index.html 
(see https://git.io/fh7NI)

The link here just goes to an 404

(Versions: @qooxdoo/compiler v1.0.0-beta.20200613-2032)

**Comment by hkollmann** [comment]
New project or old one? In it‘s older you have to change Boot.js to Index.js in your source/Boot/Index.html file

**Comment by hcarsten** [comment]
In fact an old one (the message appeared after updating to the version above). The index.html currently read as : 
`<noscript>
    <meta http-equiv="refresh" content="0; url=nojs.html"/>
  </noscript>
  ${preBootJs}
  <script type="text/javascript" src="${appPath}boot.js"></script>`

**Comment by hkollmann** [comment]
Change boot.js to index.js

**Comment by hkollmann** [comment]
If it's working now - can you close the issue?
