### ISSUE TITLE
compiler comes with an old copy of its own sources

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#749]
I just installed @qooxdoo/compiler and was trying to track down #746 `node_modules/@qooxdoo/compiler/node_modules/@qooxdoo/compiler/source/class/qx/tool/cli/api/AbstractApi.js`. This is double odd. First because the compiler is not using this as it is coming pre-compiled now and second because it is not the version used in the copy of the compiler just installed but something older ... maybe the version used to self-compile the compiler ?

**Comment by hkollmann** [comment]
This will be fixed in the next version. Npm-shrinkwrap needs to be patched too 

Von meinem iPhone gesendet

**Comment by hkollmann** [comment]
Could you please check again?

**Comment by oetiker** [comment]
yep that extra copy of the compiler source is gone ... thank you!
