### ISSUE TITLE
Failed to load ESLint config

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo-compiler#758]
Upgrading from compiler version `1.0.0-beta-20200821-0855` to version `1.0.0-beta-20200830-1953` now gives me an error when trying to execute `qx lint`. Downgrading again resolved the issue. The error seen in the console is `Error: Error: Failed to load config "@qooxdoo/qx/browser" to extend from.`  I tried updating `eslint-plugin-qx` and `eslint-config-qx` but it did not make a difference.

**Comment by hkollmann** [comment]
Should work now.
