### ISSUE TITLE
`qx migrate` is too simplistic

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#80]
_From @johnspackman on September 22, 2017 12:57_

The upgrade is very basic at the moment - notable missing support is for libraries and environment settings, both of which should be fairly easy to implement and would be really useful for a lot of projects

_Copied from original issue: qooxdoo/qooxdoo-cli#18_

**Comment by johnspackman** [comment]
_From @cboulanger on September 23, 2017 9:35_

I‘ll be looking into what it would have needed to generate by Bibliograph ˋcompile.jsonˋ from the original ˋconfig.jsonˋ. just need time! I hope I‘ll have some time in October, and could contribute that then.

**Comment by cboulanger** [comment]
see #352.

@johnspackman What are your plans on this? Does it make sense at all or is the time better invested into writing a tutorial on how to transform a `config.json` into `compile.json`? In that case, we should remove the command.

**Comment by johnspackman** [comment]
originally it was to migrate lots of settings across, but the state of the CLI now is so much more sophisticated that a lot of that migration work would be obsolete (EG you don't care about library paths for Qooxdoo any more, packages (aka contribs) would be added via the API, and the whole setup process is pretty trivial for many apps.  OTOH getting an accurate read on config.json is hard so there's a pretty good risk of migrating something that doesn't work out of the box.

I'd vote to remove the command and replace with a tutorial as you suggest

**Comment by hkollmann** [comment]
We have just removed it.
