### ISSUE TITLE
`qx create` not working properly

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#81]
_From @johnspackman on November 25, 2017 14:37_

I've noticed a few bugs with `qx create` on Windows

* the qooxdoo framework path is relative to the directory where you ran `qx create` and not relative to the new application directory; eg `qx create foo` detects my qooxdoo path as `qooxdoo/framework` but the `compile.json` should list the path as `../qooxdoo/framework'
* compile.json needs to have CRLF on Windows
* paths should use forward slashes or need to have backslashes escaped, eg the qooxdoo path of `"qooxdoo\framework"` doesnt work

_Copied from original issue: qooxdoo/qooxdoo-cli#38_

**Comment by johnspackman** [comment]
Also it would be really useful if the locale was set to include the users locale, eg at the moment it is just `[ "en" ]` but it would be good if it was `[ "en", "en_gb" ]` or `[ "en", "en_de" ]` etc; this is because the CLDR database does not provide correct date formatting information unless the locale is specified in detail, for example "en_gb" short date format comes out as d/m/y but "en" is the US version of m/d/y.

**Comment by johnspackman** [comment]
_From @cboulanger on November 25, 2017 15:5_

As to the path issue, yes, that was a problem which I avoided by using absolute paths, which is not a solution. I thought @hkollmann 's fixed that in his commits? Is that a Windows-only problem (probably not).

**Comment by johnspackman** [comment]
I dont think it is Windows specific, just that I came across this when testing on my Windows VM.

The problem is that the  path needs to be relative to the application directory, not the current directory when creating the application (the current directory is the parent of the application directory)

**Comment by johnspackman** [comment]
_From @hkollmann on November 25, 2017 19:21_

I have a patch - can be commited if the template branch is merged

**Comment by hkollmann** [comment]
qx create is using fixed node modules path now
