### ISSUE TITLE
qx contrib publish: allow overriding of version number

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#82]
_From @cboulanger on November 28, 2017 8:17_

`qx contrib publish` at the moment increments the existing version number according to the release type (major, minor, patch ...). We should  add a `-V/--version` option that allows to manually set the version number.

_Copied from original issue: qooxdoo/qooxdoo-cli#47_

**Comment by johnspackman** [comment]
_From @cboulanger on December 1, 2017 13:32_

A contrib should have a demo, which allows to see what it does and could be used in unit tests for quality control. qx contrib publish will warn if there isn't one and recommend to add it via `qx contrib init`

**Comment by johnspackman** [comment]
_From @cboulanger on December 1, 2017 15:2_

More changes: 
- `qx contrib publish` should also allow to enter a custom release message
- in the confirmation, add the release type (major, minor,...) to the confirmation message

**Comment by cboulanger** [comment]
Already implemented, closing.
