### ISSUE TITLE
Update Getting Started readme to use qooxdoo compiler

### ISSUE THREAD

**Issue by milandamen** [qooxdoo/qooxdoo-compiler#832]
When following https://github.com/qooxdoo/qooxdoo/blob/master/docs/README.md it says to install `@qooxdoo/framework` and then type `qx` to start the qooxdoo compiler, but that does not work because the framework package does not have the compiler binary. It should instead be to install `@qooxdoo/compiler` like in https://qooxdoo.org/documentation/6.0/#/development/compiler/

**Comment by cboulanger** [comment]
Hi, the README in the master branch reflects the v7 release of qooxdoo, in which the compiler has been merged into the framework. This is different from the v6 release which you are referring to. If you want to use the master branch for development, you need to build the compiler as described here: https://github.com/qooxdoo/qooxdoo/blob/master/docs/development/contribute.md#coding-the-framework
