### ISSUE TITLE
add qx serve [target]

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#84]
_From @hkollmann on November 30, 2017 19:55_

Should start a webserver and serves the build target.
So tests can be done via http://

_Copied from original issue: qooxdoo/qooxdoo-cli#53_

**Comment by johnspackman** [comment]
* it should constantly compile (equivalent to `qx compile --watch`) in the background
* selectable source vs build target
* configurable port

**Comment by hkollmann** [comment]
Done
