### ISSUE TITLE
Add option to ignore global symbols

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#86]
_From @mbgonicus on December 1, 2017 8:48_

Right now the only way to prevent warnings for undeclared globals is to add an `@ignore` flag in the single qx classes, but there is no way to state symbols that are ignored in general. 

With the old generator one could write something like
```json
      "lint-check" : {
          "allowed-globals" : [
            "d3",
            "mockup",
            "mockup_mode",
            "svg"
          ]
      }
```

I reckon we should put an option to globally ignore symbols.

_Copied from original issue: qooxdoo/qooxdoo-cli#57_

**Comment by johnspackman** [comment]
_From @hkollmann on December 1, 2017 10:29_

See this too: https://github.com/qooxdoo/qooxdoo-cli/issues/54

**Comment by mbgonicus** [comment]
@johnspackman is this solved? compare #54 and #57

**Comment by johnspackman** [comment]
don't know - @hkollmann has been working on lint

**Comment by hkollmann** [comment]
For qx lint this is working through eslint settings:

https://github.com/qooxdoo/qooxdoo-compiler/blob/master/docs/cli/compile-json.md#eslint

**Comment by cboulanger** [comment]
@johnspackman Is this "nice to have" or do you want to implement it for v6?

**Comment by hkollmann** [comment]
done with https://github.com/qooxdoo/qooxdoo-compiler/pull/421
