### ISSUE TITLE
new command: "qx contrib init"

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#87]
_From @cboulanger on December 1, 2017 13:30_

The command transforms a non-contrb library into a contrib that can be published right away, by executing the following steps:

1. add a `qooxdoo.json` file, containing `{ "libraries":{"path":"."}, "applications":{"path":"demo/default"}}`
2. creating a demo application in `demo/default`, if it doesn't already exist. 
3. consistency checks for `Manifest.json` and `compile.json`

_Copied from original issue: qooxdoo/qooxdoo-cli#58_

**Comment by cboulanger** [comment]
This is outdated. Closing.
