### ISSUE TITLE
Store GitHub API token locally

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo-compiler#88]
_From @cboulanger on December 20, 2017 7:25_

This is how PHP's composer does it:

```
Could not fetch https://api.github.com/repos/RobinHerbots/Inputmask/commits/6fcd2cf28ee111f8aadcd42a1b8d43d6f7a5c0ba, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+MB05-RiK.local+2017-12-20+0720
to retrieve a token. It will be stored in "/Users/cboulanger/.composer/auth.json" for future use by Composer.
```

_Copied from original issue: qooxdoo/qooxdoo-cli#73_

**Comment by cboulanger** [comment]
@johnspackman @hkollmann https://www.npmjs.com/package/dotenv seems to be a simple and effective solution

**Comment by oetiker** [comment]
the problem with .env is that its content is bound to end up in the actual environent. not a place where you would want your github tokens to reside since stuff that is in the environment of a process is easily stolen

**Comment by cboulanger** [comment]
True. First thing I did was to put `.env` into `.gitignore` (I use it in another context), but of course that is easily forgotten. As said before, I am happy with exporting environment variables in the shell resource file, but if you can come up with a better solution, that would be great.

**Comment by oetiker** [comment]
It is not about the file ending up in git ... that can happen to any file ... the problem is data stored in environment variables is not well protected from prying eyes of other users on the same system while the process with the environment variables is running 

```
$ cat /proc/$$/environ
```

for example

**Comment by cboulanger** [comment]
Ok, I see. I actually didn't know that, thank you. I wonder why this was never fixed, but that's a different question.

**Comment by oetiker** [comment]
one mans bug is another man's feature ... I would not want to miss this one

**Comment by cboulanger** [comment]
Well anyways :-), on my dev machine it's just me. But we SHOULD have a better option, just that I will work on the other issue todo-list and leave this one to you :-)

**Comment by oetiker** [comment]
are there other 'settings' that should get stored, or is this the only one ?

**Comment by johnspackman** [comment]
some - eg answers for the `qx create` or other defaults.  I imagine that there will be a benefit in having structured storage
